/* 手术术式库（移植自 LA-0.7.68 拓展版 src/modules/medical/surgery-library.js，纯数据 + 纯函数、零依赖）。编码/分级为源仓人工标注草案，非临床核实。 */
'use strict';

// =====================================================================
// 手术 · 术式库（SURGERY_LIBRARY）· 纯数据文件
// ---------------------------------------------------------------------
// 骨架来源（设计文档 §5.2）：手术操作分类代码**国家临床版 3.0**（基于 ICD-9-CM-3）
// 的**编码目录**。国临版只白捡两样：① 规范名 ② 编码（直接当 id，稳定键）；
// 章 → 类目 是"三层选择"的第一、二层（§5.4）。
//
// ★ 诚实性声明（必读，发布前按此抽查；口径见设计文档 §5.2 / §13 / §15 风险 1）★
//   1. 除 id / name 之外的一切字段——grade / stages / typicalMinutes / recoveryDays /
//      complications / bodyFields / capabilities / codeCandidates
//      ——**全部是本仓人工标注的草案**，**没有联网核对**，**没有临床评审**，
//      **发布前需人工抽查**（设计 §13「医学内容正确性不在自动化范围内」、
//      §15 风险 1「国临版是编码目录，恢复期 / 并发症 / 映射全要人工标」）。
//   2. codeVerified 一律 false：本仓没有联网核对条件，编码只是**照记忆写下的候选值**，
//      不保证与国临版 3.0 逐字一致。日后核对到不一致时，**只改 id / name**，
//      不要顺手改扩展字段（扩展字段是本仓自己的标注，与编码对不对无关）。
//   3. grade（一~四级）的溯源：本仓按《手术分级管理办法》的**管理口径自评**，
//      **不来自** ICD-9-CM-3 编码目录（那份目录只给名称 + 编码，不含分级）。
//      要"官方分级"必须人工逐条核（分级本身还因省 / 因院、因术式改良而异）。
//   4. 章名与章号按 ICD-9-CM-3 通行的十六分章写法（消化 = 第九章、肌肉骨骼 = 第十四章、
//      体被系统 = 第十五章）。**已知冲突**：设计文档的条目示例与
//      scripts/gen-surgery-preview.js 的静态样例写的是「第十五章 消化系统手术」
//      「第十八章 女性生殖系统手术」「第八十六章 皮肤与体表手术」，与通行章序不符
//      （且互相之间不成体系）。本文件按通行章序写，此处差异**待人工裁定**；
//      裁定后只改 chapter 字符串即可，不动 id。
//   5. typicalMinutes 是**人工估算的时长形状**（用于术中页那根轴的时间戳），
//      **不是临床计时**：core 的 surgeryStages 把它们累加成刻度 at / atText，
//      surgerySituationSheet 的 totalMinutes = 各段之和。形状口径：入室 0、
//      诱导 / 麻醉 5~15、进路短、**主要步骤最长**、清点 3~8、关腹 / 缝合中等、苏醒 10~20；
//      总时长落在可信量级（阑尾 ~68 min、直肠 Miles ~186 min、髋置换 ~126 min）。
//      这些秒表数字**需人工抽查**（设计 §13 / §15）。
//   6. codeCandidates 是**给人工核对用的候选编码**（从最可能到次可能，主编码不在其中）；
//      缺省表示只有主编码一个候选。只给本仓标注时**没把握**的编码加了它，
//      有把握的那些不加（保持数据干净）。
//   7. complications 的 weight 是**同一术式内的相对权重**（同一术式内不必和为 1），
//      只进 core 的确定性加权判定（§7）；风险数字**只许出现在术前谈话**，
//      判定结果上不许出现任何成功率 / 判定语（§1.8 / §7 数字口径）。
//   8. capabilities 只写**真有引擎映射**的两类：canGestate / canImpregnate（口径 **0.7.27 放宽**：凡"把生殖器官**整体拿掉**、或使其永久失效"的术式都写 —— 62.4 / 68.4 / 68.51 / 65.6；单侧切除、剔除、活检类**仍不写**，只在 note 里说明）。
//      没有映射就不写该字段（§6.3「不给出空勾选」）；有映射的由面板默认勾选、留痕。
//      **0.7.5 起这条从"写在文件头的约定"升级成测试钉住的契约**（`test/surgery-illness-map107`）：
//      ① 有 capabilities 的条目**只能是"器官被整体拿掉"那三条**（62.4 双侧睾丸 / 68.4 子宫全切 / 65.6 双侧卵巢）；
//      ② 凡是**解剖上挨着生殖器官 / 容易被误以为影响生育**的术式（脊柱髓核摘除、单侧输卵管切除、
//         前列腺电切、囊肿剥除、包皮环切、精索静脉结扎、产科那三条、乳腺肿物、阴茎延长、处女膜修补、隆胸、
//         子宫肌瘤剔除、腺叶切除、脾切除、直肠切除…）——**note 里必须写明"改"或"为什么不改"**。
//         判据是"读者会不会以为漏了"，不是"医学上有没有关系"。
//   9. 意愿·改造型（ext）按 §5.4 走 elective：不产生 condition，只写身体档案字段
//      与（有映射时的）引擎能力。仙侠改造术（血肉重塑 / 灵根改铸 / 夺舍式改造）
//      **按 §5.5 不进库**，留给用户 / AI 落池，本文件一条都不收。
//      扩展条目的 id 沿用本仓既有样例的写法：断骨增高术 = X.height、赛博义体植入术 = X.prosth
//      （见 scripts/gen-surgery-preview.js 与 0.6.85 的验收探针）；其余扩展条目用可读后缀。
//  10. 覆盖 = 「高频 30~60 条」的第一批（§15 风险 1 的建议口径）；后续按同一 schema 追加。
// =====================================================================

const SURGERY_INTENTS = ['therapeutic', 'emergency', 'obstetric', 'elective'];
const SURGERY_ANESTHESIAS = ['general', 'regional', 'local', 'none'];
const SURGERY_GRADES = [1, 2, 3, 4];


// =====================================================================
// 0.7.25（术式库数据轮）：**阶段表模板化**（设计文档 §3.6 那根轴 + 本文件 §5.2 条目结构）
//   四个入路模板：open 开放 / lap 腹腔镜 / surface 体表表浅 / endo 内镜腔道。
//   每条术式只声明：用哪个模板 + 主要步骤叫什么 + 自己的差异（drop 不用哪几段、rename 改名、
//   minutes 改时长、add 模板里没有的段）。**判据**：解析出来的 stages 必须仍是 6~10 段、
//   首段 room_in（0 分钟）、末段 wake|out、段 id 唯一（test/surgery-library85 ② 钉着）。
// =====================================================================
// 共享阶段词表：**库内出现过的所有段 id**（模板是它的有序子集；新段要先加进词表，
// 免得同一个意思在不同术式里写成两个 id —— 0.7.25 加断言时就抓出过 4 个漏网的）。
const STAGE_VOCAB = [
  'anesthesia',
  'bandage',
  'closure',
  'count',
  'deliver',
  'explore',
  'exposure',
  'fixation',
  'hemostasis',
  'implant',
  'incision',
  'induction',
  'inspect',
  'interface',
  'main',
  'marking',
  'osteotomy',
  'pneumo',
  'position',
  'prep',
  'reduce',
  'repair',
  'room_in',
  'scope',
  'stoma',
  'tumescent',
  'verify',
  'wake',
  'withdraw',
];
export const STAGE_TEMPLATES = {
  open: [
    ['room_in', '入室', 0],
    ['anesthesia', '麻醉', 8],
    ['induction', '麻醉诱导', 8],
    ['position', '体位·消毒铺巾', 5],
    ['prep', '消毒铺巾', 4],
    ['incision', '切口入路', 4],
    ['explore', '探查', 8],
    ['exposure', '显露', 6],
    ['main', '主要步骤', 22],
    ['count', '清点·止血', 4],
    ['verify', '核对·确认', 4],
    ['closure', '关腹·逐层缝合', 8],
    ['wake', '苏醒', 7],
    ['stoma', '造口成形', 8, true],
    ['reduce', '复位', 10, true],
    ['deliver', '娩出胎儿', 6, true],
    ['repair', '修补', 12, true],
    ['osteotomy', '截骨', 20, true],
    ['fixation', '固定（内 / 外固定）', 15, true],
  ],
  lap: [
    ['room_in', '入室', 0],
    ['induction', '麻醉诱导', 8],
    ['position', '体位·消毒铺巾', 5],
    ['prep', '气腹准备', 3],
    ['pneumo', '建立气腹·穿刺器置入', 6],
    ['explore', '镜下探查', 8],
    ['exposure', '解剖·显露', 6],
    ['main', '主要步骤', 25],
    ['count', '清点·止血·冲洗', 5],
    ['verify', '核对·确认', 4],
    ['closure', '解除气腹·缝合戳孔', 6],
    ['wake', '苏醒', 8],
  ],
  surface: [
    ['room_in', '入室', 0],
    ['anesthesia', '局部麻醉', 4],
    ['prep', '消毒铺巾', 3],
    ['marking', '标记·设计', 3],
    ['incision', '切开·显露', 3],
    ['exposure', '显露', 3],
    ['main', '主要步骤', 14],
    ['verify', '核对·确认', 3],
    ['closure', '止血·缝合', 6],
    ['bandage', '包扎·固定', 3],
    ['wake', '苏醒', 3],
    ['tumescent', '肿胀液注射', 8, true],
    ['implant', '植入物置入', 10, true],
    ['interface', '接口 / 界面处理', 6, true],
  ],
  endo: [
    ['room_in', '入室', 0],
    ['anesthesia', '镇静/麻醉', 5],
    ['induction', '麻醉诱导', 6],
    ['position', '体位', 3],
    ['prep', '器械准备', 3],
    ['scope', '器械入路·观察', 5],
    ['inspect', '镜下检查', 5],
    ['main', '主要步骤', 12],
    ['hemostasis', '止血/处理', 4],
    ['verify', '核对·确认', 3],
    ['withdraw', '退镜', 3],
    ['closure', '收尾', 3],
    ['wake', '苏醒', 6],
  ],
};

export function stageTable(template, mainName, opts) {
  const tpl = STAGE_TEMPLATES[template];
  if (!tpl) throw new Error('未知阶段表模板：' + template);
  for (const [id] of tpl) if (STAGE_VOCAB.indexOf(id) < 0) throw new Error('模板段 id 不在词表里：' + id);
  const o = opts || {};
  const drop = new Set(o.drop || []);
  const rename = o.rename || {};
  const minutes = o.minutes || {};
  const out = [];
  const keep = new Set(o.keep || []);
  for (const row of tpl) {
    const id = row[0], name = row[1], min = row[2], optional = row[3] === true;
    if (drop.has(id)) continue;
    if (optional && !keep.has(id)) continue;   // 可选段：默认不用（要用就 keep 或 add）
    out.push({ id: id, name: Object.prototype.hasOwnProperty.call(rename, id) ? rename[id] : name, typicalMinutes: Object.prototype.hasOwnProperty.call(minutes, id) ? minutes[id] : min });
  }
  if (mainName) { const main = out.filter(s => s.id === 'main')[0]; if (main) main.name = mainName; }
  for (const add of (o.add || [])) {
    if (STAGE_VOCAB.indexOf(add[1]) < 0) throw new Error('新增段 id 不在词表里：' + add[1] + '（先加进 STAGE_VOCAB）');
    const node = { id: add[1], name: add[2], typicalMinutes: add[3] };
    const at = add[0] ? out.findIndex(s => s.id === add[0]) : out.length;
    if (at < 0) out.push(node); else out.splice(at + 1, 0, node);
  }
  return out;
}
export const SURGERY_LIBRARY = [
  // ===== 第九章 消化系统手术 =====
  {
    id: '47.0',
    name: '阑尾切除术',
    alias: ['阑尾切除', '阑尾炎手术'],
    catalog: 'national',
    codeVerified: false,
    chapter: '第九章 消化系统手术',
    category: '阑尾手术',
    grade: 2,
    intents: ['therapeutic', 'emergency'],
    anesthesia: 'general',
    recoveryDays: 7,
    stages: stageTable('open', '阑尾切除·荷包缝合', { drop: ['anesthesia', 'prep', 'exposure', 'verify'], rename: { incision: '切皮入路', explore: '探查·寻找阑尾', main: '阑尾切除·荷包缝合', closure: '关腹' }, minutes: { explore: 10 } }),
    complications: [
      { id: 'ssi', name: '切口感染', weight: 0.30, severity: 'mild', whenDays: 3, bodyFields: ['temperature'], note: '切口红肿渗液、低热' },
      { id: 'intra_abscess', name: '腹腔残余脓肿', weight: 0.12, severity: 'moderate', whenDays: 5, bodyFields: ['temperature', 'heartRate'], note: '术后持续发热、右下腹压痛' },
      { id: 'ileus', name: '术后肠麻痹', weight: 0.18, severity: 'mild', whenDays: 2, bodyFields: ['temperature'], note: '腹胀、迟迟不排气' },
      { id: 'adhesion', name: '腹腔粘连', weight: 0.20, severity: 'moderate', whenDays: 30, bodyFields: ['surgeryHistory'], note: '远期慢性腹痛、再次手术困难' },
    ],
    bodyFields: ['surgeryHistory', 'temperature'],
    note: '急症与择期皆常见；穿孔者本仓口径为分级与风险上调一档',
  },
  {
    id: '53.0',
    name: '腹股沟疝修补术',
    alias: ['疝修补', '腹股沟疝手术'],
    catalog: 'national',
    codeVerified: false,
    chapter: '第九章 消化系统手术',
    category: '疝手术',
    grade: 2,
    intents: ['therapeutic', 'emergency'],
    anesthesia: 'regional',
    recoveryDays: 7,
    stages: stageTable('open', '疝囊高位结扎·修补', { drop: ['induction', 'prep', 'explore', 'exposure', 'count', 'verify'], rename: { anesthesia: '麻醉穿刺·平面测试', incision: '腹股沟切口', main: '疝囊高位结扎·修补', closure: '逐层关闭', wake: '麻醉恢复·出室' }, minutes: { position: 4, main: 16, closure: 6, wake: 4 } }),
    complications: [
      { id: 'ssi', name: '切口感染', weight: 0.20, severity: 'mild', whenDays: 3, bodyFields: ['temperature'], note: '切口红肿、缝线处渗液' },
      { id: 'hematoma', name: '阴囊血肿', weight: 0.25, severity: 'mild', whenDays: 2, bodyFields: ['surgeryHistory'], note: '阴囊肿胀发硬、坠痛' },
      { id: 'recurrence', name: '疝复发', weight: 0.15, severity: 'moderate', whenDays: 30, bodyFields: ['surgeryHistory'], note: '远期同侧再现可复性包块' },
      { id: 'urinary_retention', name: '术后尿潴留', weight: 0.20, severity: 'mild', whenDays: 1, bodyFields: ['temperature'], note: '麻醉后膀胱充盈、排不出尿' },
    ],
    bodyFields: ['surgeryHistory'],
    note: '嵌顿 / 绞窄属急症口径（intents 含 emergency）；补片修补与缝线修补共用本条',
  },
  {
    id: '51.23',
    name: '腹腔镜胆囊切除术',
    alias: ['腹腔镜胆囊切除', '胆囊切除'],
    catalog: 'national',
    codeVerified: false,
    chapter: '第九章 消化系统手术',
    category: '胆囊手术',
    grade: 3,
    intents: ['therapeutic', 'emergency'],
    anesthesia: 'general',
    recoveryDays: 7,
    stages: stageTable('lap', '胆囊管与血管离断·胆囊剥离', { drop: ['position', 'prep', 'exposure', 'verify'], rename: { explore: '镜下探查·解剖三角', main: '胆囊管与血管离断·胆囊剥离' }, minutes: { induction: 10, pneumo: 8, main: 30, closure: 8, wake: 7 } }),
    complications: [
      { id: 'bile_leak', name: '胆漏', weight: 0.10, severity: 'moderate', whenDays: 4, bodyFields: ['temperature', 'heartRate'], note: '引流管持续胆汁样液体、腹痛' },
      { id: 'ssi', name: '戳孔感染', weight: 0.18, severity: 'mild', whenDays: 4, bodyFields: ['temperature'], note: '戳孔红肿、少量渗液' },
      { id: 'retained_stone', name: '胆管残余结石', weight: 0.08, severity: 'moderate', whenDays: 10, bodyFields: ['temperature'], note: '术后再次胆绞痛、黄疸' },
      { id: 'pneumonia', name: '术后肺部感染', weight: 0.12, severity: 'moderate', whenDays: 3, bodyFields: ['temperature', 'respiratoryRate'], note: '气腹后咳痰无力、发热' },
    ],
    bodyFields: ['surgeryHistory', 'temperature'],
    note: '急性胆囊炎可急症入路；中转开腹由 core 按手艺档与粘连权重判，不由库固定',
  },
  {
    id: '43.7',
    name: '胃大部切除术',
    alias: ['胃部分切除', '毕Ⅱ式胃切除术'],
    catalog: 'national',
    codeVerified: false,
    codeCandidates: ['43.6', '43.81'],
    chapter: '第九章 消化系统手术',
    category: '胃手术',
    grade: 3,
    intents: ['therapeutic', 'emergency'],
    anesthesia: 'general',
    recoveryDays: 21,
    stages: stageTable('open', '胃切除·胃肠吻合', { drop: ['anesthesia', 'prep', 'exposure', 'verify'], rename: { incision: '上腹切口', explore: '探查·游离', main: '胃切除·胃肠吻合', closure: '关腹' }, minutes: { induction: 10, position: 8, incision: 5, explore: 15, main: 60, count: 6, closure: 12, wake: 12 } }),
    complications: [
      { id: 'anastomotic_leak', name: '吻合口漏', weight: 0.12, severity: 'severe', whenDays: 6, bodyFields: ['temperature', 'heartRate'], note: '术后高热、腹膜刺激征' },
      { id: 'anastomotic_bleeding', name: '吻合口出血', weight: 0.15, severity: 'moderate', whenDays: 2, bodyFields: ['bloodPressure', 'heartRate'], note: '胃管引流出鲜血、心率增快' },
      { id: 'dumping', name: '倾倒综合征', weight: 0.30, severity: 'moderate', whenDays: 14, bodyFields: ['heartRate', 'weight'], note: '进食后心悸出汗、腹泻' },
      { id: 'ileus', name: '术后肠麻痹', weight: 0.20, severity: 'mild', whenDays: 3, bodyFields: ['temperature'], note: '腹胀、肠鸣音弱' },
    ],
    bodyFields: ['surgeryHistory', 'weight', 'temperature'],
    note: '溃疡穿孔 / 大出血为急症口径；胃恶性肿瘤的全胃切除不在本条（另立条目）',
  },
  {
    id: '48.5',
    name: '腹会阴联合直肠切除术',
    alias: ['Miles手术', '直肠癌根治术'],
    catalog: 'national',
    codeVerified: false,
    chapter: '第九章 消化系统手术',
    category: '直肠手术',
    grade: 4,
    intents: ['therapeutic'],
    anesthesia: 'general',
    recoveryDays: 30,
    stages: stageTable('open', '直肠切除·会阴部切除', { drop: ['anesthesia', 'prep', 'exposure', 'verify'], rename: { position: '截石位·消毒铺巾', incision: '下腹切口', explore: '探查·游离直肠', main: '直肠切除·会阴部切除', closure: '关腹·会阴缝合' }, minutes: { induction: 12, position: 10, incision: 6, explore: 20, main: 70, count: 6, closure: 20, wake: 22 }, add: [['main', 'stoma', '乙状结肠造口成形', 20]] }),
    complications: [
      { id: 'stoma_complication', name: '造口并发症', weight: 0.35, severity: 'moderate', whenDays: 7, bodyFields: ['surgeryHistory'], note: '造口回缩 / 周围皮炎 / 狭窄' },
      { id: 'ssi', name: '会阴切口感染', weight: 0.20, severity: 'mild', whenDays: 4, bodyFields: ['temperature'], note: '会阴伤口红肿渗液' },
      { id: 'sexual_dysfunction', name: '性功能与排尿障碍', weight: 0.25, severity: 'moderate', whenDays: 30, bodyFields: ['reproductiveState'], note: '盆腔自主神经损伤所致' },
      { id: 'adhesion', name: '盆腹腔粘连', weight: 0.30, severity: 'moderate', whenDays: 45, bodyFields: ['surgeryHistory'], note: '远期慢性盆腔痛、梗阻风险' },
    ],
    bodyFields: ['surgeryHistory', 'weight'],
    note: '本仓口径：本条不改引擎能力（不涉及生殖腺），造口属身体档案既往史记述',
  },
  {
    id: '49.4',
    name: '痔切除术',
    alias: ['痔切除', '外剥内扎术'],
    catalog: 'national',
    codeVerified: false,
    codeCandidates: ['49.45', '49.46'],
    chapter: '第九章 消化系统手术',
    category: '肛门手术',
    grade: 1,
    intents: ['therapeutic'],
    anesthesia: 'regional',
    recoveryDays: 14,
    stages: stageTable('open', '外剥内扎·切除', { drop: ['induction', 'prep', 'incision', 'explore', 'count', 'verify'], rename: { anesthesia: '麻醉穿刺·平面测试', position: '截石位·消毒铺巾', exposure: '显露痔核', main: '外剥内扎·切除', closure: '止血·包扎', wake: '麻醉恢复·出室' }, minutes: { anesthesia: 6, position: 4, exposure: 4, main: 8, closure: 3, wake: 4 } }),
    complications: [
      { id: 'bleeding', name: '创面出血', weight: 0.20, severity: 'moderate', whenDays: 1, bodyFields: ['bloodPressure', 'heartRate'], note: '排便后滴血、量大需处理' },
      { id: 'urinary_retention', name: '术后尿潴留', weight: 0.30, severity: 'mild', whenDays: 1, bodyFields: ['temperature'], note: '肛门疼痛反射性排尿困难' },
      { id: 'anal_stenosis', name: '肛门狭窄', weight: 0.10, severity: 'moderate', whenDays: 21, bodyFields: ['surgeryHistory'], note: '瘢痕挛缩致排便变细' },
      { id: 'ssi', name: '创面感染', weight: 0.12, severity: 'mild', whenDays: 4, bodyFields: ['temperature'], note: '创面分泌物增多、疼痛加重' },
    ],
    bodyFields: ['surgeryHistory'],
    note: '设计文档 §3.6 的"换药 / 清创走全套会变折磨"正对应本条（一级、恢复快）',
  },

  // ===== 第八章 造血和淋巴系统手术 =====
  {
    id: '41.5',
    name: '脾切除术',
    alias: ['脾切除', '脾破裂手术'],
    catalog: 'national',
    codeVerified: false,
    chapter: '第八章 造血和淋巴系统手术',
    category: '脾手术',
    grade: 4,
    intents: ['therapeutic', 'emergency'],
    anesthesia: 'general',
    recoveryDays: 14,
    stages: stageTable('open', '脾游离·脾蒂离断', { drop: ['anesthesia', 'prep', 'exposure', 'verify'], rename: { incision: '左上腹切口', explore: '探查·控制脾蒂', main: '脾游离·脾蒂离断', closure: '关腹' }, minutes: { induction: 10, position: 6, incision: 5, explore: 15, main: 40, count: 5, closure: 10, wake: 12 } }),
    complications: [
      { id: 'hemorrhage', name: '腹腔内出血', weight: 0.15, severity: 'severe', whenDays: 0, bodyFields: ['bloodPressure', 'heartRate'], note: '引流血性液增多、血压下降' },
      { id: 'subphrenic_abscess', name: '膈下脓肿', weight: 0.12, severity: 'moderate', whenDays: 6, bodyFields: ['temperature'], note: '术后弛张热、左上腹压痛' },
      { id: 'thrombocytosis', name: '血小板升高', weight: 0.40, severity: 'mild', whenDays: 10, bodyFields: ['bloodPressure'], note: '脾切除后反应性升高，需监测' },
      { id: 'atelectasis', name: '左下肺不张', weight: 0.20, severity: 'mild', whenDays: 2, bodyFields: ['respiratoryRate', 'temperature'], note: '膈肌抬高、呼吸音减弱' },
    ],
    bodyFields: ['surgeryHistory', 'bloodPressure', 'heartRate'],
    note: '外伤性脾破裂为急症口径；本仓口径：脾切除不改 canGestate / canImpregnate',
  },

  // ===== 第二章 内分泌系统手术 =====
  {
    id: '06.2',
    name: '单侧甲状腺叶切除术',
    alias: ['甲状腺腺叶切除', '甲状腺瘤手术'],
    catalog: 'national',
    codeVerified: false,
    codeCandidates: ['06.39'],
    chapter: '第二章 内分泌系统手术',
    category: '甲状腺手术',
    grade: 3,
    intents: ['therapeutic'],
    anesthesia: 'general',
    recoveryDays: 7,
    stages: stageTable('open', '腺叶切除', { drop: ['anesthesia', 'prep', 'explore', 'count', 'verify'], rename: { position: '颈过伸位·消毒铺巾', incision: '颈部低位切口', exposure: '显露腺体·保护喉返神经', main: '腺叶切除', closure: '止血·逐层关闭', wake: '麻醉恢复·出室' }, minutes: { induction: 10, position: 6, incision: 5, exposure: 10, main: 30, wake: 8 } }),
    complications: [
      { id: 'hoarseness', name: '声音嘶哑', weight: 0.20, severity: 'mild', whenDays: 2, bodyFields: ['surgeryHistory'], note: '喉返神经牵拉或损伤' },
      { id: 'hypocalcemia', name: '低钙抽搐', weight: 0.10, severity: 'moderate', whenDays: 2, bodyFields: ['temperature'], note: '口周麻木、手足搐搦' },
      { id: 'bleeding', name: '术后出血压迫气管', weight: 0.10, severity: 'severe', whenDays: 0, bodyFields: ['bloodPressure', 'heartRate'], note: '颈部肿胀、呼吸困难' },
      { id: 'ssi', name: '切口感染', weight: 0.10, severity: 'mild', whenDays: 4, bodyFields: ['temperature'], note: '切口红肿、渗液' },
    ],
    bodyFields: ['surgeryHistory', 'weight', 'heartRate'],
    note: '腺叶切除一般不影响生殖能力，故不写 capabilities',
  },

  // ===== 第十五章 体被系统手术 =====
  {
    id: '85.21',
    name: '乳腺肿物切除术',
    alias: ['乳房肿物切除', '乳腺纤维瘤切除术'],
    catalog: 'national',
    codeVerified: false,
    codeCandidates: ['85.22', '85.23'],
    chapter: '第十五章 体被系统手术',
    category: '乳房手术',
    grade: 2,
    intents: ['therapeutic'],
    anesthesia: 'local',
    recoveryDays: 7,
    stages: stageTable('surface', '肿物切除·送检', { drop: ['marking', 'incision', 'exposure', 'verify', 'bandage'], rename: { main: '肿物切除·送检', wake: '观察出室' }, minutes: { anesthesia: 5, prep: 4, main: 15, closure: 4, wake: 4 } }),
    complications: [
      { id: 'ssi', name: '切口感染', weight: 0.15, severity: 'mild', whenDays: 3, bodyFields: ['temperature'], note: '切口红肿渗液' },
      { id: 'hematoma', name: '术区血肿', weight: 0.20, severity: 'mild', whenDays: 2, bodyFields: ['surgeryHistory'], note: '术区肿胀、压痛' },
      { id: 'fat_necrosis', name: '脂肪液化', weight: 0.12, severity: 'mild', whenDays: 7, bodyFields: ['temperature'], note: '切口渗出淡黄色液体' },
    ],
    bodyFields: ['surgeryHistory'],
    note: '乳腺恶性肿瘤的根治性切除未收录（另立条目）；本条为良性肿物局部切除；不改引擎能力（乳腺不是生殖腺）',
  },

  // ===== 第十四章 肌肉骨骼系统手术 =====
  {
    id: '79.3',
    name: '骨折切开复位内固定术',
    alias: ['骨折内固定', '切开复位内固定'],
    catalog: 'national',
    codeVerified: false,
    codeCandidates: ['79.1', '79.2'],
    chapter: '第十四章 肌肉骨骼系统手术',
    category: '骨折复位与内固定',
    grade: 3,
    intents: ['therapeutic', 'emergency'],
    anesthesia: 'regional',
    recoveryDays: 90,
    stages: stageTable('surface', '骨折切开复位内固定术', { drop: ['marking', 'incision', 'main', 'bandage'], rename: { anesthesia: '麻醉穿刺·平面测试', prep: '体位·消毒铺巾', exposure: '显露骨折端', verify: '透视确认·止血', closure: '逐层关闭', wake: '麻醉恢复·出室' }, minutes: { anesthesia: 12, prep: 5, exposure: 8, verify: 5, closure: 10, wake: 12 }, add: [['exposure', 'reduce', '复位·内固定', 30]] }),
    complications: [
      { id: 'infection', name: '骨与内固定感染', weight: 0.12, severity: 'severe', whenDays: 7, bodyFields: ['temperature', 'heartRate'], note: '伤口深部感染、内固定存留难题' },
      { id: 'nonunion', name: '骨不连', weight: 0.10, severity: 'severe', whenDays: 60, bodyFields: ['surgeryHistory'], note: '复查见骨折端无愈合' },
      { id: 'nerve_injury', name: '神经损伤', weight: 0.08, severity: 'moderate', whenDays: 1, bodyFields: ['surgeryHistory'], note: '术后远端麻木、活动受限' },
      { id: 'dvt', name: '下肢深静脉血栓', weight: 0.15, severity: 'severe', whenDays: 7, bodyFields: ['surgeryHistory'], note: '患肢肿胀疼痛、肺栓塞风险' },
    ],
    bodyFields: ['surgeryHistory', 'height'],
    note: '本条为通用条目（部位由报告里的 findings 记）；开放性骨折属急症口径',
  },
  {
    id: '81.51',
    name: '全髋关节置换术',
    alias: ['髋关节置换', '人工髋关节置换'],
    catalog: 'national',
    codeVerified: false,
    chapter: '第十四章 肌肉骨骼系统手术',
    category: '关节置换术',
    grade: 4,
    intents: ['therapeutic'],
    anesthesia: 'regional',
    recoveryDays: 90,
    stages: stageTable('surface', '股骨头切除·假体植入', { drop: ['marking', 'bandage'], rename: { anesthesia: '麻醉穿刺·平面测试', prep: '侧卧位·消毒铺巾', incision: '后外侧切口', exposure: '显露髋关节', main: '股骨头切除·假体植入', verify: '复位·测试活动度', closure: '逐层关闭', wake: '麻醉恢复·出室' }, minutes: { anesthesia: 12, prep: 8, incision: 5, exposure: 12, main: 55, verify: 5, closure: 15, wake: 14 } }),
    complications: [
      { id: 'dislocation', name: '假体脱位', weight: 0.10, severity: 'severe', whenDays: 7, bodyFields: ['surgeryHistory'], note: '体位不当后患髋剧痛、不能活动' },
      { id: 'prosthesis_loosening', name: '假体松动', weight: 0.15, severity: 'moderate', whenDays: 60, bodyFields: ['surgeryHistory'], note: '远期负重痛、需翻修' },
      { id: 'dvt', name: '下肢深静脉血栓', weight: 0.20, severity: 'severe', whenDays: 7, bodyFields: ['surgeryHistory'], note: '患肢肿胀、肺栓塞风险' },
      { id: 'infection', name: '假体周围感染', weight: 0.08, severity: 'critical', whenDays: 14, bodyFields: ['temperature', 'heartRate'], note: '持续发热、窦道形成' },
    ],
    bodyFields: ['surgeryHistory', 'height', 'weight'],
    note: '四级手术；本仓口径：置换不改身体档案的身高数值，只记既往史',
  },
  {
    id: '81.54',
    name: '全膝关节置换术',
    alias: ['膝关节置换', '人工膝关节置换'],
    catalog: 'national',
    codeVerified: false,
    chapter: '第十四章 肌肉骨骼系统手术',
    category: '关节置换术',
    grade: 4,
    intents: ['therapeutic'],
    anesthesia: 'regional',
    recoveryDays: 90,
    stages: stageTable('surface', '截骨·假体植入', { drop: ['marking', 'bandage'], rename: { anesthesia: '麻醉穿刺·平面测试', prep: '仰卧位·消毒铺巾·止血带', incision: '膝前正中切口', exposure: '显露膝关节', main: '截骨·假体植入', verify: '复位·测试力线', closure: '逐层关闭·放松止血带', wake: '麻醉恢复·出室' }, minutes: { anesthesia: 12, prep: 8, incision: 5, exposure: 10, main: 58, verify: 5, closure: 15, wake: 13 } }),
    complications: [
      { id: 'prosthesis_loosening', name: '假体松动', weight: 0.15, severity: 'moderate', whenDays: 60, bodyFields: ['surgeryHistory'], note: '远期负重痛、需翻修' },
      { id: 'dvt', name: '下肢深静脉血栓', weight: 0.20, severity: 'severe', whenDays: 7, bodyFields: ['surgeryHistory'], note: '患肢肿胀、肺栓塞风险' },
      { id: 'infection', name: '假体周围感染', weight: 0.08, severity: 'critical', whenDays: 14, bodyFields: ['temperature'], note: '持续发热、切口不愈' },
      { id: 'stiffness', name: '膝关节僵硬', weight: 0.30, severity: 'moderate', whenDays: 30, bodyFields: ['surgeryHistory'], note: '屈伸范围不足、康复疼痛' },
    ],
    bodyFields: ['surgeryHistory', 'height', 'weight'],
    note: '四级手术；康复期长，恢复期天数本仓暂按 90 天',
  },
  {
    id: '80.51',
    name: '腰椎间盘髓核摘除术',
    alias: ['腰椎间盘摘除', '髓核摘除术'],
    catalog: 'national',
    codeVerified: false,
    chapter: '第十四章 肌肉骨骼系统手术',
    category: '脊柱手术',
    grade: 4,
    intents: ['therapeutic'],
    anesthesia: 'general',
    recoveryDays: 42,
    stages: stageTable('open', '开窗·髓核摘除', { drop: ['anesthesia', 'prep', 'explore', 'count', 'verify'], rename: { position: '俯卧位·消毒铺巾', incision: '后正中切口', exposure: '显露椎板与神经根', main: '开窗·髓核摘除', closure: '止血·逐层关闭', wake: '麻醉恢复·出室' }, minutes: { induction: 10, position: 6, exposure: 10, main: 35, wake: 8 } }),
    complications: [
      { id: 'nerve_root_injury', name: '神经根损伤', weight: 0.10, severity: 'moderate', whenDays: 1, bodyFields: ['surgeryHistory'], note: '术后放射痛加重或感觉减退' },
      { id: 'dural_tear', name: '硬膜撕裂', weight: 0.12, severity: 'moderate', whenDays: 1, bodyFields: ['surgeryHistory'], note: '术中脑脊液漏、术后头痛' },
      { id: 'recurrence', name: '椎间盘突出复发', weight: 0.15, severity: 'moderate', whenDays: 30, bodyFields: ['surgeryHistory'], note: '同节段再次突出' },
      { id: 'ssi', name: '切口感染', weight: 0.08, severity: 'mild', whenDays: 4, bodyFields: ['temperature'], note: '切口红肿、渗液' },
    ],
    bodyFields: ['surgeryHistory'],
    note: '四级手术；术后偶见逆行射精，属并发症叙述（进正文），不改 canImpregnate —— 精子照常产生',
  },

  // ===== 第十一章 男性生殖器官手术 =====
  {
    id: '60.29',
    name: '经尿道前列腺电切术',
    alias: ['前列腺电切', 'TURP'],
    catalog: 'national',
    codeVerified: false,
    chapter: '第十一章 男性生殖器官手术',
    category: '前列腺手术',
    grade: 3,
    intents: ['therapeutic'],
    anesthesia: 'regional',
    recoveryDays: 14,
    stages: stageTable('endo', '电切·止血', { drop: ['induction', 'prep', 'inspect', 'hemostasis', 'verify', 'withdraw'], rename: { anesthesia: '麻醉穿刺·平面测试', position: '截石位·消毒铺巾', scope: '置镜·观察', main: '电切·止血', closure: '留置导尿·持续冲洗', wake: '麻醉恢复·出室' }, minutes: { anesthesia: 10, position: 5, main: 20, closure: 5, wake: 8 } }),
    complications: [
      { id: 'hemorrhage', name: '术后出血', weight: 0.20, severity: 'moderate', whenDays: 0, bodyFields: ['bloodPressure', 'heartRate'], note: '冲洗液转红、血块堵塞尿管' },
      { id: 'urinary_incontinence', name: '暂时性尿失禁', weight: 0.15, severity: 'moderate', whenDays: 14, bodyFields: ['surgeryHistory'], note: '拔管后控尿不佳' },
      { id: 'urethral_stricture', name: '尿道狭窄', weight: 0.12, severity: 'moderate', whenDays: 30, bodyFields: ['surgeryHistory'], note: '排尿变细、需扩张' },
      { id: 'retrograde_ejaculation', name: '逆行射精', weight: 0.35, severity: 'mild', whenDays: 14, bodyFields: ['reproductiveState'], note: '射精时精液逆流入膀胱' },
    ],
    bodyFields: ['surgeryHistory', 'temperature'],
    note: '本仓口径：TURP 不改 canImpregnate（仍可产生精子，只是射精方式改变）',
  },
  {
    id: '63.1',
    name: '精索静脉高位结扎术',
    alias: ['精索静脉结扎', '精索静脉曲张手术'],
    catalog: 'national',
    codeVerified: false,
    chapter: '第十一章 男性生殖器官手术',
    category: '精索手术',
    grade: 2,
    intents: ['therapeutic'],
    anesthesia: 'regional',
    recoveryDays: 14,
    stages: stageTable('surface', '精索静脉高位结扎', { drop: ['marking', 'exposure', 'verify', 'bandage'], rename: { anesthesia: '麻醉穿刺·平面测试', prep: '体位·消毒铺巾', incision: '腹股沟切口', main: '精索静脉高位结扎', closure: '止血·逐层关闭', wake: '麻醉恢复·出室' }, minutes: { anesthesia: 8, prep: 4, incision: 4, main: 12, closure: 5, wake: 6 } }),
    complications: [
      { id: 'hydrocele', name: '鞘膜积液', weight: 0.20, severity: 'mild', whenDays: 14, bodyFields: ['surgeryHistory'], note: '术后阴囊逐渐肿大、坠胀' },
      { id: 'recurrence', name: '静脉曲张复发', weight: 0.15, severity: 'moderate', whenDays: 60, bodyFields: ['surgeryHistory'], note: '侧支循环建立后再现' },
      { id: 'ssi', name: '切口感染', weight: 0.10, severity: 'mild', whenDays: 3, bodyFields: ['temperature'], note: '切口红肿渗液' },
    ],
    bodyFields: ['surgeryHistory', 'reproductiveState'],
    note: '常用于改善精液质量，属治病口径（不是 elective）；不改引擎能力 —— 结扎的是静脉，不是输精管',
  },
  {
    id: '64.0',
    name: '包皮环切术',
    alias: ['包皮环切', '割包皮'],
    catalog: 'national',
    codeVerified: false,
    chapter: '第十一章 男性生殖器官手术',
    category: '阴茎手术',
    grade: 1,
    intents: ['therapeutic'],
    anesthesia: 'local',
    recoveryDays: 14,
    stages: stageTable('surface', '环切·止血', { drop: ['marking', 'incision', 'exposure', 'verify', 'bandage'], rename: { anesthesia: '阴茎根部阻滞麻醉', main: '环切·止血', closure: '缝合·包扎', wake: '观察出室' }, minutes: { main: 8, closure: 3, wake: 4 } }),
    complications: [
      { id: 'bleeding', name: '创面出血', weight: 0.15, severity: 'mild', whenDays: 1, bodyFields: ['surgeryHistory'], note: '夜间勃起后渗血' },
      { id: 'ssi', name: '创面感染', weight: 0.15, severity: 'mild', whenDays: 3, bodyFields: ['temperature'], note: '创面红肿、脓性分泌物' },
      { id: 'phimosis_recurrence', name: '包皮口狭窄', weight: 0.08, severity: 'mild', whenDays: 30, bodyFields: ['surgeryHistory'], note: '瘢痕挛缩致上翻受限' },
    ],
    bodyFields: ['surgeryHistory'],
    note: '本仓按治病口径收（包茎 / 反复包皮龟头炎指征）；纯美容动机走 ext 的另一条；不改引擎能力',
  },
  {
    id: '62.4',
    name: '双侧睾丸切除术',
    alias: ['双侧睾丸切除', '去势术'],
    catalog: 'national',
    codeVerified: false,
    codeCandidates: ['62.41', '62.42'],
    chapter: '第十一章 男性生殖器官手术',
    category: '睾丸手术',
    grade: 3,
    intents: ['therapeutic'],
    anesthesia: 'general',
    recoveryDays: 14,
    stages: stageTable('open', '双侧睾丸切除·止血', { drop: ['anesthesia', 'position', 'explore', 'exposure', 'count', 'verify'], rename: { prep: '体位·消毒铺巾', incision: '阴囊切口', main: '双侧睾丸切除·止血', closure: '缝合·包扎', wake: '麻醉恢复·出室' }, minutes: { main: 15, closure: 5 } }),
    complications: [
      { id: 'hematoma', name: '阴囊血肿', weight: 0.25, severity: 'mild', whenDays: 2, bodyFields: ['surgeryHistory'], note: '阴囊迅速肿大、发硬' },
      { id: 'ssi', name: '切口感染', weight: 0.15, severity: 'mild', whenDays: 4, bodyFields: ['temperature'], note: '切口红肿、渗液' },
      { id: 'hormone_withdrawal', name: '雄激素撤退反应', weight: 0.50, severity: 'moderate', whenDays: 14, bodyFields: ['temperature', 'heartRate'], note: '潮热、乏力、情绪低落' },
    ],
    bodyFields: ['surgeryHistory', 'reproductiveState'],
    capabilities: { canImpregnate: false },
    note: '真有引擎映射（不再产生精子）——按 §6.3 只登记事实 + 面板明说，不静默执行',
  },

  // ===== 第十二章 女性生殖器官手术 =====
  {
    id: '68.4',
    name: '子宫全切除术',
    alias: ['子宫全切', '全子宫切除术'],
    catalog: 'national',
    codeVerified: false,
    chapter: '第十二章 女性生殖器官手术',
    category: '子宫手术',
    grade: 4,
    intents: ['therapeutic'],
    anesthesia: 'general',
    recoveryDays: 42,
    stages: stageTable('open', '子宫血管处理·子宫切除', { drop: ['anesthesia', 'prep', 'exposure', 'verify'], rename: { position: '截石位·消毒铺巾·导尿', incision: '下腹切口', explore: '探查·处理圆韧带', main: '子宫血管处理·子宫切除', closure: '关腹·阴道残端缝合' }, minutes: { induction: 10, position: 8, incision: 5, explore: 12, main: 55, count: 5, closure: 15, wake: 12 } }),
    complications: [
      { id: 'hemorrhage', name: '术中术后出血', weight: 0.18, severity: 'severe', whenDays: 0, bodyFields: ['bloodPressure', 'heartRate'], note: '盆腔创面渗血、血压下降' },
      { id: 'urinary_injury', name: '输尿管 / 膀胱损伤', weight: 0.08, severity: 'severe', whenDays: 1, bodyFields: ['surgeryHistory'], note: '术中解剖致损伤、术后漏尿' },
      { id: 'pelvic_infection', name: '盆腔感染', weight: 0.15, severity: 'moderate', whenDays: 5, bodyFields: ['temperature'], note: '术后发热、盆腔压痛' },
      { id: 'vault_prolapse', name: '阴道残端脱垂', weight: 0.10, severity: 'moderate', whenDays: 60, bodyFields: ['reproductiveState'], note: '远期残端下移、坠胀感' },
    ],
    bodyFields: ['surgeryHistory', 'reproductiveState'],
    capabilities: { canGestate: false },
    note: '真有引擎映射（不再能妊娠）——§6.3：唯一出口 cycle-adapter.setCapability，默认勾选',
  },
  {
    id: '68.29',
    name: '子宫肌瘤剔除术',
    alias: ['肌瘤剔除', '子宫肌瘤剜除术'],
    catalog: 'national',
    codeVerified: false,
    chapter: '第十二章 女性生殖器官手术',
    category: '子宫手术',
    grade: 3,
    intents: ['therapeutic'],
    anesthesia: 'general',
    recoveryDays: 30,
    stages: stageTable('open', '肌瘤剔除·子宫肌层缝合', { drop: ['anesthesia', 'prep', 'exposure', 'verify'], rename: { position: '体位·消毒铺巾·导尿', incision: '下腹切口', explore: '探查·显露肌瘤', main: '肌瘤剔除·子宫肌层缝合', closure: '关腹' }, minutes: { induction: 10, position: 7, incision: 5, explore: 10, main: 45, count: 6, closure: 15, wake: 10 } }),
    complications: [
      { id: 'hemorrhage', name: '术中术后出血', weight: 0.25, severity: 'moderate', whenDays: 0, bodyFields: ['bloodPressure', 'heartRate'], note: '肌瘤床渗血、子宫收缩差' },
      { id: 'recurrence', name: '肌瘤复发', weight: 0.20, severity: 'moderate', whenDays: 60, bodyFields: ['reproductiveState'], note: '保留子宫故有复发可能' },
      { id: 'adhesion', name: '盆腔粘连', weight: 0.30, severity: 'moderate', whenDays: 45, bodyFields: ['surgeryHistory'], note: '远期慢性盆腔痛、影响受孕' },
      { id: 'ssi', name: '切口感染', weight: 0.10, severity: 'mild', whenDays: 4, bodyFields: ['temperature'], note: '切口红肿渗液' },
    ],
    bodyFields: ['surgeryHistory', 'reproductiveState'],
    note: '保留子宫 → 不写 canGestate（本仓口径：保留生育器官就不动该布尔）',
  },
  {
    id: '65.2',
    name: '卵巢囊肿剥除术',
    alias: ['卵巢囊肿剥除', '卵巢囊肿切除术'],
    catalog: 'national',
    codeVerified: false,
    codeCandidates: ['65.25', '65.29'],
    chapter: '第十二章 女性生殖器官手术',
    category: '卵巢手术',
    grade: 3,
    intents: ['therapeutic', 'emergency'],
    anesthesia: 'general',
    recoveryDays: 21,
    stages: stageTable('lap', '囊肿剥除·卵巢成形', { drop: ['position', 'prep', 'exposure', 'verify'], rename: { explore: '镜下探查·暴露囊肿', main: '囊肿剥除·卵巢成形' }, minutes: { induction: 10, pneumo: 8, main: 30, count: 4, closure: 8, wake: 7 } }),
    complications: [
      { id: 'hemorrhage', name: '创面出血', weight: 0.15, severity: 'moderate', whenDays: 0, bodyFields: ['bloodPressure'], note: '卵巢创面渗血' },
      { id: 'adhesion', name: '盆腔粘连', weight: 0.25, severity: 'moderate', whenDays: 45, bodyFields: ['surgeryHistory'], note: '远期慢性盆腔痛、影响排卵拾卵' },
      { id: 'recurrence', name: '囊肿复发', weight: 0.15, severity: 'moderate', whenDays: 60, bodyFields: ['reproductiveState'], note: '同侧或对侧再发' },
      { id: 'pelvic_infection', name: '盆腔感染', weight: 0.10, severity: 'moderate', whenDays: 5, bodyFields: ['temperature'], note: '术后发热、下腹痛' },
    ],
    bodyFields: ['surgeryHistory', 'reproductiveState'],
    note: '囊肿扭转 / 破裂属急症口径；剥除保留卵巢组织 → 不改引擎能力（本仓口径：保留生殖器官就不动那两个布尔）',
  },
  {
    id: '65.6',
    name: '双侧卵巢切除术',
    alias: ['双侧卵巢切除', '女性去势术'],
    catalog: 'national',
    codeVerified: false,
    codeCandidates: ['65.61', '65.63', '65.5'],
    chapter: '第十二章 女性生殖器官手术',
    category: '卵巢手术',
    grade: 3,
    intents: ['therapeutic'],
    anesthesia: 'general',
    recoveryDays: 30,
    stages: stageTable('open', '双侧附件离断·切除', { drop: ['anesthesia', 'prep', 'exposure', 'count', 'verify'], rename: { position: '体位·消毒铺巾·导尿', incision: '下腹切口', explore: '探查·游离卵巢血管蒂', main: '双侧附件离断·切除', closure: '止血·逐层关腹' }, minutes: { induction: 10, position: 6, incision: 5, explore: 10, main: 30, wake: 6 } }),
    complications: [
      { id: 'hemorrhage', name: '盆腹腔出血', weight: 0.15, severity: 'moderate', whenDays: 0, bodyFields: ['bloodPressure', 'heartRate'], note: '卵巢血管蒂渗血' },
      { id: 'hormone_withdrawal', name: '雌激素撤退反应', weight: 0.45, severity: 'moderate', whenDays: 14, bodyFields: ['temperature', 'heartRate'], note: '潮热盗汗、情绪波动' },
      { id: 'pelvic_infection', name: '盆腔感染', weight: 0.12, severity: 'moderate', whenDays: 5, bodyFields: ['temperature'], note: '术后发热、盆腔压痛' },
    ],
    bodyFields: ['surgeryHistory', 'reproductiveState'],
    capabilities: { canGestate: false },
    note: '真有引擎映射（不再能妊娠）——本条是本仓口径下最需要人工确认的条目之一',
  },
  {
    id: '66.62',
    name: '输卵管妊娠切除术',
    alias: ['宫外孕手术', '输卵管妊娠切除'],
    catalog: 'national',
    codeVerified: false,
    codeCandidates: ['66.4', '66.01'],
    chapter: '第十二章 女性生殖器官手术',
    category: '输卵管手术',
    grade: 3,
    intents: ['therapeutic', 'emergency'],
    anesthesia: 'general',
    recoveryDays: 30,
    stages: stageTable('lap', '输卵管切除·取胚', { drop: ['position', 'prep', 'exposure', 'verify'], rename: { explore: '探查·确认病灶侧', main: '输卵管切除·取胚', count: '清点·止血·冲洗腹腔' }, minutes: { pneumo: 7, main: 32, closure: 8, wake: 7 } }),
    complications: [
      { id: 'hemorrhage', name: '腹腔内出血', weight: 0.25, severity: 'severe', whenDays: 0, bodyFields: ['bloodPressure', 'heartRate'], note: '破裂型出血、失血性休克风险' },
      { id: 'adhesion', name: '盆腔粘连', weight: 0.25, severity: 'moderate', whenDays: 45, bodyFields: ['surgeryHistory'], note: '影响日后受孕' },
      { id: 'recurrent_ectopic', name: '再次异位妊娠', weight: 0.15, severity: 'severe', whenDays: 60, bodyFields: ['reproductiveState'], note: '对侧输卵管或同侧残端再发' },
    ],
    bodyFields: ['surgeryHistory', 'reproductiveState'],
    note: '本仓口径：切除单侧输卵管不改 canGestate（仍可妊娠，只是概率下降）',
  },
  {
    id: '69.0',
    name: '产后清宫术',
    alias: ['产后清宫', '宫腔残留清宫术'],
    catalog: 'national',
    codeVerified: false,
    codeCandidates: ['69.02', '75.4'],
    chapter: '第十二章 女性生殖器官手术',
    category: '子宫手术',
    grade: 2,
    intents: ['obstetric', 'emergency'],
    anesthesia: 'regional',
    recoveryDays: 14,
    stages: stageTable('surface', '宫颈扩张·清宫', { drop: ['marking', 'incision', 'exposure', 'verify', 'bandage'], rename: { anesthesia: '宫颈阻滞·静脉镇痛', prep: '截石位·消毒铺巾', main: '宫颈扩张·清宫', closure: '检查宫腔·止血', wake: '观察出室' }, minutes: { anesthesia: 5, prep: 4, main: 12, closure: 5, wake: 6 } }),
    complications: [
      { id: 'hemorrhage', name: '子宫出血', weight: 0.20, severity: 'moderate', whenDays: 0, bodyFields: ['bloodPressure', 'heartRate'], note: '宫缩乏力、出血量增多' },
      { id: 'uterine_perforation', name: '子宫穿孔', weight: 0.05, severity: 'severe', whenDays: 0, bodyFields: ['bloodPressure'], note: '探针超出宫腔深度、剧痛' },
      { id: 'endometritis', name: '子宫内膜炎', weight: 0.15, severity: 'moderate', whenDays: 4, bodyFields: ['temperature'], note: '术后发热、恶露异味' },
      { id: 'adhesion', name: '宫腔粘连', weight: 0.20, severity: 'moderate', whenDays: 45, bodyFields: ['surgeryHistory'], note: '远期经量减少、继发不孕' },
    ],
    bodyFields: ['surgeryHistory', 'reproductiveState'],
    note: '章按解剖归第十二章（子宫），intent 按产科事件给 obstetric（章与意图是两个轴）；清宫不是切除子宫 → 不改引擎能力',
  },

  // ===== 第十三章 产科操作 =====
  {
    id: '74.1',
    name: '子宫下段剖宫产术',
    alias: ['剖宫产', '剖腹产'],
    catalog: 'national',
    codeVerified: false,
    chapter: '第十三章 产科操作',
    category: '剖宫产术',
    grade: 3,
    intents: ['obstetric', 'emergency'],
    anesthesia: 'regional',
    recoveryDays: 42,
    stages: stageTable('surface', '子宫下段剖宫产术', { drop: ['marking', 'exposure', 'main', 'verify', 'bandage'], rename: { anesthesia: '麻醉穿刺·平面测试', prep: '体位·消毒铺巾·导尿', incision: '切皮入腹', closure: '逐层关腹', wake: '麻醉恢复·出室' }, minutes: { anesthesia: 10, prep: 6, incision: 5, closure: 10, wake: 8 }, add: [['incision', 'deliver', '子宫切开·娩出胎儿', 10], ['deliver', 'repair', '胎盘娩出·子宫缝合', 20]] }),
    complications: [
      { id: 'postpartum_hemorrhage', name: '产后出血', weight: 0.15, severity: 'severe', whenDays: 0, bodyFields: ['bloodPressure', 'heartRate'], note: '宫缩乏力、出血量超过阈值' },
      { id: 'endometritis', name: '子宫切口感染', weight: 0.15, severity: 'moderate', whenDays: 4, bodyFields: ['temperature'], note: '术后发热、子宫压痛' },
      { id: 'wound_dehiscence', name: '切口愈合不良', weight: 0.10, severity: 'moderate', whenDays: 6, bodyFields: ['temperature'], note: '脂肪液化、切口裂开' },
      { id: 'dvt', name: '下肢深静脉血栓', weight: 0.08, severity: 'severe', whenDays: 7, bodyFields: ['surgeryHistory'], note: '产褥期高凝状态下更易发生' },
    ],
    bodyFields: ['surgeryHistory', 'reproductiveState', 'weight'],
    note: '结算仍归本仓的 delivery（§2 产科只读引用、不写病症）；本模块不接管产科结算；剖宫产不摘除子宫 → 不改引擎能力（下次仍可妊娠，只是多有瘢痕）',
  },
  {
    id: '73.6',
    name: '会阴侧切缝合术',
    alias: ['会阴侧切', '侧切缝合'],
    catalog: 'national',
    codeVerified: false,
    chapter: '第十三章 产科操作',
    category: '助产操作',
    grade: 1,
    intents: ['obstetric'],
    anesthesia: 'local',
    recoveryDays: 14,
    stages: stageTable('surface', '切开·助产', { drop: ['marking', 'incision', 'exposure', 'verify', 'bandage'], rename: { anesthesia: '局部浸润麻醉', prep: '体位·消毒铺巾', main: '切开·助产', closure: '缝合·止血', wake: '观察出室' }, minutes: { anesthesia: 5, prep: 4, main: 10, closure: 7, wake: 6 } }),
    complications: [
      { id: 'wound_infection', name: '切口感染', weight: 0.15, severity: 'mild', whenDays: 4, bodyFields: ['temperature'], note: '伤口红肿、疼痛加重' },
      { id: 'hematoma', name: '会阴血肿', weight: 0.12, severity: 'mild', whenDays: 2, bodyFields: ['surgeryHistory'], note: '会阴肿胀、坐立困难' },
      { id: 'dehiscence', name: '伤口裂开', weight: 0.08, severity: 'moderate', whenDays: 5, bodyFields: ['temperature'], note: '缝线脱落、伤口分离' },
      { id: 'dyspareunia', name: '性交疼痛', weight: 0.20, severity: 'mild', whenDays: 45, bodyFields: ['reproductiveState'], note: '瘢痕牵拉所致' },
    ],
    bodyFields: ['surgeryHistory', 'reproductiveState'],
    note: '与分娩同场进行；§2 产科只读引用、不写病症；本模块只记手术报告；不改引擎能力',
  },

  // ===== 第六章 呼吸系统手术 =====
  {
    id: '34.04',
    name: '胸腔闭式引流术',
    alias: ['胸腔闭式引流', '胸引'],
    catalog: 'national',
    codeVerified: false,
    codeCandidates: ['34.91', '34.09'],
    chapter: '第六章 呼吸系统手术',
    category: '胸膜腔手术',
    grade: 1,
    intents: ['therapeutic', 'emergency'],
    anesthesia: 'local',
    recoveryDays: 7,
    stages: stageTable('surface', '切开置管·接水封瓶', { drop: ['marking', 'incision', 'exposure', 'verify', 'bandage'], rename: { prep: '体位·消毒铺巾', main: '切开置管·接水封瓶', closure: '固定导管·包扎', wake: '观察出室' }, minutes: { main: 8, closure: 3 } }),
    complications: [
      { id: 'bleeding', name: '肋间血管出血', weight: 0.15, severity: 'moderate', whenDays: 0, bodyFields: ['bloodPressure', 'heartRate'], note: '引流出血性液体增多' },
      { id: 'infection', name: '胸腔感染', weight: 0.12, severity: 'moderate', whenDays: 4, bodyFields: ['temperature', 'respiratoryRate'], note: '发热、胸痛、引流液浑浊' },
      { id: 'reexpansion_edema', name: '复张性肺水肿', weight: 0.08, severity: 'severe', whenDays: 1, bodyFields: ['respiratoryRate'], note: '大量排气后气促、湿啰音' },
    ],
    bodyFields: ['surgeryHistory', 'respiratoryRate', 'bloodPressure'],
    note: '气胸 / 血胸急症常用；术前信息少、流程短，正是 §3.6 里"短流程"的一类',
  },

  // ===== 第七章 心血管系统手术 =====
  {
    id: '38.59',
    name: '大隐静脉高位结扎剥脱术',
    alias: ['大隐静脉剥脱', '静脉曲张手术'],
    catalog: 'national',
    codeVerified: false,
    chapter: '第七章 心血管系统手术',
    category: '静脉手术',
    grade: 2,
    intents: ['therapeutic'],
    anesthesia: 'regional',
    recoveryDays: 21,
    stages: stageTable('surface', '高位结扎·剥脱', { drop: ['marking', 'exposure', 'verify', 'bandage'], rename: { anesthesia: '麻醉穿刺·平面测试', prep: '标记·消毒铺巾', incision: '腹股沟切口', main: '高位结扎·剥脱', closure: '缝合·加压包扎', wake: '麻醉恢复·出室' }, minutes: { anesthesia: 10, prep: 5, incision: 4, main: 20, wake: 8 } }),
    complications: [
      { id: 'bleeding', name: '皮下血肿', weight: 0.15, severity: 'mild', whenDays: 1, bodyFields: ['surgeryHistory'], note: '沿剥脱隧道淤血' },
      { id: 'nerve_injury', name: '隐神经损伤', weight: 0.12, severity: 'moderate', whenDays: 1, bodyFields: ['surgeryHistory'], note: '小腿内侧麻木' },
      { id: 'dvt', name: '下肢深静脉血栓', weight: 0.10, severity: 'severe', whenDays: 7, bodyFields: ['surgeryHistory'], note: '患肢肿胀、肺栓塞风险' },
      { id: 'ssi', name: '切口感染', weight: 0.10, severity: 'mild', whenDays: 4, bodyFields: ['temperature'], note: '腹股沟切口红肿渗液' },
    ],
    bodyFields: ['surgeryHistory'],
    note: '下肢静脉曲张的确定性手术；剥脱范围按曲张静脉走行定（本条不细分术式改良）',
  },

  // ===== 第三章 眼部手术 =====
  {
    id: '13.41',
    name: '白内障超声乳化摘除术',
    alias: ['白内障超声乳化', '白内障手术'],
    catalog: 'national',
    codeVerified: false,
    chapter: '第三章 眼部手术',
    category: '晶状体手术',
    grade: 2,
    intents: ['therapeutic'],
    anesthesia: 'local',
    recoveryDays: 14,
    stages: stageTable('surface', '超声乳化·吸除', { drop: ['marking', 'incision', 'exposure', 'verify', 'bandage'], rename: { anesthesia: '表面·局部麻醉', prep: '消毒铺巾·开睑', main: '超声乳化·吸除', closure: '包扎术眼', wake: '观察出室' }, minutes: { anesthesia: 5, prep: 4, main: 15, closure: 3, wake: 5 } }),
    complications: [
      { id: 'endophthalmitis', name: '眼内炎', weight: 0.02, severity: 'critical', whenDays: 3, bodyFields: ['temperature'], note: '术眼剧痛、视力骤降（急症）' },
      { id: 'capsule_rupture', name: '后囊膜破裂', weight: 0.08, severity: 'moderate', whenDays: 0, bodyFields: ['surgeryHistory'], note: '术中晶状体核坠落风险' },
      { id: 'corneal_edema', name: '角膜水肿', weight: 0.25, severity: 'mild', whenDays: 1, bodyFields: ['surgeryHistory'], note: '术后视物模糊、角膜混浊' },
    ],
    bodyFields: ['surgeryHistory'],
    note: '常与人工晶状体植入同期；本仓口径：晶状体植入不改任何档案字段与能力',
  },

  // ===== 第五章 鼻、口、咽部手术 =====
  {
    id: '28.2',
    name: '扁桃体切除术',
    alias: ['扁桃体切除', '扁桃体摘除术'],
    catalog: 'national',
    codeVerified: false,
    chapter: '第五章 鼻、口、咽部手术',
    category: '咽部手术',
    grade: 2,
    intents: ['therapeutic'],
    anesthesia: 'general',
    recoveryDays: 14,
    stages: stageTable('endo', '剥离·切除', { drop: ['anesthesia', 'prep', 'scope', 'inspect', 'verify', 'withdraw', 'closure'], rename: { position: '体位·开口器', main: '剥离·切除', hemostasis: '止血·观察创面', wake: '麻醉恢复·出室' }, minutes: { induction: 8, position: 4, main: 15, hemostasis: 6, wake: 8 } }),
    complications: [
      { id: 'hemorrhage', name: '术后出血', weight: 0.15, severity: 'moderate', whenDays: 1, bodyFields: ['bloodPressure', 'heartRate'], note: '术后 24 小时内创面渗血' },
      { id: 'ssi', name: '创面感染', weight: 0.12, severity: 'mild', whenDays: 4, bodyFields: ['temperature'], note: '咽痛加重、发热' },
      { id: 'swallowing_pain', name: '吞咽疼痛', weight: 0.40, severity: 'mild', whenDays: 3, bodyFields: ['temperature'], note: '进食困难、拒食' },
    ],
    bodyFields: ['surgeryHistory', 'temperature'],
    note: '本仓口径：扁桃体切除不改任何引擎能力（免疫相关叙述走正文，不进能力布尔）',
  },

  // ===== 第十五章 体被系统手术（体表） =====
  {
    id: '86.3',
    name: '体表肿物切除术',
    alias: ['体表肿物切除', '皮肤肿物切除术'],
    catalog: 'national',
    codeVerified: false,
    chapter: '第十五章 体被系统手术',
    category: '皮肤及皮下组织手术',
    grade: 1,
    intents: ['therapeutic'],
    anesthesia: 'local',
    recoveryDays: 7,
    stages: stageTable('surface', '肿物切除·送检', { drop: ['marking', 'incision', 'exposure', 'verify', 'bandage'], rename: { main: '肿物切除·送检', closure: '缝合·包扎', wake: '观察出室' }, minutes: { main: 8, closure: 3, wake: 4 } }),
    complications: [
      { id: 'ssi', name: '切口感染', weight: 0.12, severity: 'mild', whenDays: 3, bodyFields: ['temperature'], note: '切口红肿渗液' },
      { id: 'keloid', name: '瘢痕增生', weight: 0.15, severity: 'mild', whenDays: 30, bodyFields: ['surgeryHistory'], note: '切口处瘢痕隆起、发痒' },
      { id: 'recurrence', name: '肿物复发', weight: 0.10, severity: 'moderate', whenDays: 60, bodyFields: ['surgeryHistory'], note: '同部位再次出现（切缘残留）' },
    ],
    bodyFields: ['surgeryHistory'],
    note: '名称按规范医学名写（不用"小手术"这类模糊名），便于病症库按名锚定',
  },
  {
    id: '86.22',
    name: '清创缝合术',
    alias: ['清创', '伤口缝合'],
    catalog: 'national',
    codeVerified: false,
    chapter: '第十五章 体被系统手术',
    category: '创口处理',
    grade: 1,
    intents: ['therapeutic', 'emergency'],
    anesthesia: 'local',
    recoveryDays: 10,
    stages: stageTable('surface', '清创·去除失活组织', { drop: ['marking', 'incision', 'exposure', 'verify', 'bandage'], rename: { prep: '冲洗·消毒铺巾', main: '清创·去除失活组织', closure: '缝合·包扎', wake: '观察出室' }, minutes: { anesthesia: 3, main: 6, closure: 3, wake: 2 } }),
    complications: [
      { id: 'ssi', name: '伤口感染', weight: 0.20, severity: 'mild', whenDays: 3, bodyFields: ['temperature'], note: '伤口红肿、脓性分泌物' },
      { id: 'dehiscence', name: '伤口裂开', weight: 0.12, severity: 'moderate', whenDays: 5, bodyFields: ['temperature'], note: '张力大或感染后缝线脱落' },
      { id: 'scarring', name: '瘢痕形成', weight: 0.25, severity: 'mild', whenDays: 30, bodyFields: ['surgeryHistory'], note: '创缘对合不佳致瘢痕明显' },
    ],
    bodyFields: ['surgeryHistory', 'temperature'],
    note: '从术式库直接进（§2 救急路）：刚受伤、course 为 injury 时走这条，不挑病症',
  },

  // ===== 扩展（catalog:ext）· 本仓人工标注，无国临版编码 =====
  {
    id: 'x-blepharoplasty',
    legacyId: 'X.blepharoplasty',   // 0.7.25 起扩展条目用 x-<slug>；旧 id（X.*）留着兼容已落盘的数据
    name: '重睑成形术',
    alias: ['重睑术', '双眼皮手术'],
    catalog: 'ext',
    codeVerified: false,
    chapter: '第三章 眼部手术',
    category: '眼睑手术',
    grade: 1,
    intents: ['elective'],
    anesthesia: 'local',
    recoveryDays: 14,
    stages: stageTable('surface', '切开·成形', { drop: ['prep', 'incision', 'exposure', 'verify', 'bandage'], rename: { marking: '设计·画线', main: '切开·成形', closure: '缝合·包扎', wake: '观察出室' }, minutes: { anesthesia: 5, marking: 5, main: 18, closure: 4, wake: 8 } }),
    complications: [
      { id: 'asymmetry', name: '双侧不对称', weight: 0.25, severity: 'mild', whenDays: 14, bodyFields: ['surgeryHistory'], note: '消肿后两侧宽窄不一致' },
      { id: 'hematoma', name: '眼睑血肿', weight: 0.20, severity: 'mild', whenDays: 2, bodyFields: ['surgeryHistory'], note: '皮下淤血、肿胀明显' },
      { id: 'keloid', name: '瘢痕增生', weight: 0.10, severity: 'mild', whenDays: 30, bodyFields: ['surgeryHistory'], note: '切口线瘢痕隆起' },
    ],
    bodyFields: ['surgeryHistory'],
    note: '意愿·改造型（elective）：不产生 condition，只写身体档案既往史；分级为本仓自评',
  },
  {
    id: 'x-rhinoplasty',
    legacyId: 'X.rhinoplasty',   // 0.7.25 起扩展条目用 x-<slug>；旧 id（X.*）留着兼容已落盘的数据
    name: '隆鼻术',
    alias: ['鼻整形', '假体隆鼻'],
    catalog: 'ext',
    codeVerified: false,
    chapter: '第五章 鼻、口、咽部手术',
    category: '鼻部手术',
    grade: 2,
    intents: ['elective'],
    anesthesia: 'general',
    recoveryDays: 21,
    stages: stageTable('lap', '腔隙剥离·假体置入', { drop: ['position', 'pneumo', 'explore', 'exposure', 'count'], rename: { prep: '消毒铺巾·设计', main: '腔隙剥离·假体置入', verify: '外形确认·止血', closure: '缝合·外固定', wake: '麻醉恢复·出室' }, minutes: { induction: 10, prep: 8, main: 32, verify: 5, closure: 5, wake: 10 } }),
    complications: [
      { id: 'implant_displacement', name: '假体移位', weight: 0.20, severity: 'moderate', whenDays: 30, bodyFields: ['surgeryHistory'], note: '假体偏斜、鼻背不对称' },
      { id: 'infection', name: '术区感染', weight: 0.10, severity: 'moderate', whenDays: 5, bodyFields: ['temperature'], note: '鼻部红肿热痛' },
      { id: 'rejection', name: '假体排异', weight: 0.08, severity: 'severe', whenDays: 14, bodyFields: ['temperature'], note: '持续渗液、需取出假体' },
      { id: 'dissatisfaction', name: '外形不满意', weight: 0.30, severity: 'mild', whenDays: 30, bodyFields: ['surgeryHistory'], note: '与预期不符、要求修复' },
    ],
    bodyFields: ['surgeryHistory'],
    note: '意愿·改造型；本仓口径：隆鼻不改任何档案数值字段（只在 surgeryHistory 留痕）',
  },
  {
    id: 'x-liposuction',
    legacyId: 'X.liposuction',   // 0.7.25 起扩展条目用 x-<slug>；旧 id（X.*）留着兼容已落盘的数据
    name: '吸脂术',
    alias: ['脂肪抽吸术', '抽脂'],
    catalog: 'ext',
    codeVerified: false,
    chapter: '第十五章 体被系统手术',
    category: '皮下脂肪抽吸',
    grade: 2,
    intents: ['elective'],
    anesthesia: 'general',
    recoveryDays: 30,
    stages: stageTable('lap', '负压抽吸·塑形', { drop: ['position', 'pneumo', 'explore', 'exposure', 'count', 'verify'], rename: { prep: '标记·消毒铺巾', main: '负压抽吸·塑形', closure: '加压包扎', wake: '麻醉恢复·出室' }, minutes: { induction: 10, prep: 8, main: 45, wake: 12 }, add: [['prep', 'tumescent', '肿胀液注射', 15]] }),
    complications: [
      { id: 'seroma', name: '血清肿', weight: 0.25, severity: 'mild', whenDays: 5, bodyFields: ['surgeryHistory'], note: '抽吸区积液、波动感' },
      { id: 'contour_irregularity', name: '皮肤凹凸不平', weight: 0.35, severity: 'mild', whenDays: 45, bodyFields: ['waist', 'hip'], note: '抽吸层次不均所致' },
      { id: 'ssi', name: '术区感染', weight: 0.10, severity: 'mild', whenDays: 4, bodyFields: ['temperature'], note: '穿刺口红肿渗液' },
      { id: 'fat_embolism', name: '脂肪栓塞', weight: 0.03, severity: 'critical', whenDays: 1, bodyFields: ['respiratoryRate', 'heartRate'], note: '大范围抽吸的罕见急症' },
    ],
    bodyFields: ['surgeryHistory', 'weight', 'waist', 'hip'],
    note: '意愿·改造型；档案字段落点按 §14.5 写回门逐项勾选（默认全不勾）',
  },
  {
    id: 'x-augmentation-mammoplasty',
    legacyId: 'X.augmentation_mammoplasty',   // 0.7.25 起扩展条目用 x-<slug>；旧 id（X.*）留着兼容已落盘的数据
    name: '隆胸术',
    alias: ['假体隆胸', '乳房增大成形术'],
    catalog: 'ext',
    codeVerified: false,
    chapter: '第十五章 体被系统手术',
    category: '乳房手术',
    grade: 3,
    intents: ['elective'],
    anesthesia: 'general',
    recoveryDays: 42,
    stages: stageTable('lap', '腔隙剥离·假体置入', { drop: ['position', 'pneumo', 'explore', 'exposure', 'count'], rename: { prep: '体位·消毒铺巾·设计', main: '腔隙剥离·假体置入', verify: '对称性确认·止血', closure: '缝合·加压包扎', wake: '麻醉恢复·出室' }, minutes: { induction: 10, prep: 8, main: 45, verify: 5, closure: 8, wake: 12 } }),
    complications: [
      { id: 'capsular_contracture', name: '包膜挛缩', weight: 0.25, severity: 'moderate', whenDays: 60, bodyFields: ['bust'], note: '乳房变硬、外形改变' },
      { id: 'implant_rupture', name: '假体破裂', weight: 0.10, severity: 'moderate', whenDays: 60, bodyFields: ['bust'], note: '远期假体完整性失效' },
      { id: 'ssi', name: '术区感染', weight: 0.10, severity: 'mild', whenDays: 4, bodyFields: ['temperature'], note: '切口红肿、发热' },
      { id: 'sensory_change', name: '乳头感觉异常', weight: 0.20, severity: 'mild', whenDays: 30, bodyFields: ['bust'], note: '感觉减退或过敏' },
    ],
    bodyFields: ['surgeryHistory', 'bust', 'cup'],
    note: '意愿·改造型；本仓口径：不映射任何引擎能力（隆胸不影响生育），只走档案写回门',
  },
  {
    id: 'x-penile-lengthening',
    legacyId: 'X.penile_lengthening',   // 0.7.25 起扩展条目用 x-<slug>；旧 id（X.*）留着兼容已落盘的数据
    name: '阴茎延长术',
    alias: ['阴茎延长', '悬韧带松解术'],
    catalog: 'ext',
    codeVerified: false,
    chapter: '第十一章 男性生殖器官手术',
    category: '阴茎手术',
    grade: 3,
    intents: ['elective'],
    anesthesia: 'regional',
    recoveryDays: 42,
    stages: stageTable('surface', '悬韧带切断·延长固定', { drop: ['marking', 'incision', 'exposure', 'verify', 'bandage'], rename: { anesthesia: '麻醉穿刺·平面测试', prep: '消毒铺巾·设计', main: '悬韧带切断·延长固定', closure: '缝合·包扎', wake: '麻醉恢复·出室' }, minutes: { anesthesia: 8, prep: 5, main: 25, closure: 5, wake: 7 } }),
    complications: [
      { id: 'hematoma', name: '术区血肿', weight: 0.25, severity: 'mild', whenDays: 2, bodyFields: ['surgeryHistory'], note: '耻骨上区淤血肿胀' },
      { id: 'ssi', name: '切口感染', weight: 0.12, severity: 'mild', whenDays: 4, bodyFields: ['temperature'], note: '切口红肿渗液' },
      { id: 'erectile_dysfunction', name: '勃起功能受影响', weight: 0.15, severity: 'severe', whenDays: 30, bodyFields: ['reproductiveState'], note: '勃起角度改变或功能下降' },
      { id: 'scar_contracture', name: '瘢痕挛缩', weight: 0.20, severity: 'moderate', whenDays: 45, bodyFields: ['surgeryHistory'], note: '牵拉不适、长度回缩' },
    ],
    bodyFields: ['surgeryHistory'],
    note: '意愿·改造型；本仓口径：不改 canImpregnate（不影响精子产生），也不改档案数值字段',
  },
  {
    id: 'x-hymenorraphy',
    legacyId: 'X.hymenorraphy',   // 0.7.25 起扩展条目用 x-<slug>；旧 id（X.*）留着兼容已落盘的数据
    name: '处女膜修补术',
    alias: ['处女膜修补', '处女膜成形术'],
    catalog: 'ext',
    codeVerified: false,
    chapter: '第十二章 女性生殖器官手术',
    category: '阴道手术',
    grade: 1,
    intents: ['elective'],
    anesthesia: 'local',
    recoveryDays: 14,
    stages: stageTable('surface', '裂口修剪·缝合', { drop: ['marking', 'incision', 'exposure', 'verify', 'bandage'], rename: { prep: '截石位·消毒铺巾', main: '裂口修剪·缝合', closure: '检查·止血', wake: '观察出室' }, minutes: { prep: 4, main: 15, closure: 4, wake: 5 } }),
    complications: [
      { id: 'ssi', name: '术区感染', weight: 0.15, severity: 'mild', whenDays: 3, bodyFields: ['temperature'], note: '局部红肿、分泌物增多' },
      { id: 'dehiscence', name: '缝合处裂开', weight: 0.20, severity: 'moderate', whenDays: 7, bodyFields: ['reproductiveState'], note: '缝线脱落、修补失败' },
      { id: 'stenosis', name: '环口狭窄', weight: 0.10, severity: 'moderate', whenDays: 30, bodyFields: ['reproductiveState'], note: '缝合过紧致开口变小' },
    ],
    bodyFields: ['surgeryHistory', 'reproductiveState'],
    note: '意愿·改造型；本仓口径：不改 canGestate（不影响妊娠），也不改任何解剖布尔',
  },
  {
    id: 'x-height',
    legacyId: 'X.height',   // 0.7.25 起扩展条目用 x-<slug>；旧 id（X.*）留着兼容已落盘的数据
    name: '断骨增高术',
    alias: ['肢体延长术', '骨延长术'],
    catalog: 'ext',
    codeVerified: false,
    chapter: '第十四章 肌肉骨骼系统手术',
    category: '肢体延长术',
    grade: 4,
    intents: ['elective'],
    anesthesia: 'regional',
    recoveryDays: 120,
    stages: stageTable('surface', '断骨增高术', { drop: ['marking', 'incision', 'exposure', 'main', 'bandage'], rename: { anesthesia: '麻醉穿刺·平面测试', prep: '体位·消毒铺巾', verify: '透视确认力线', closure: '切口关闭·包扎', wake: '麻醉恢复·出室' }, minutes: { anesthesia: 12, prep: 8, verify: 5, closure: 10, wake: 18 }, add: [['prep', 'osteotomy', '截骨', 30], ['osteotomy', 'fixation', '外固定架 / 髓内钉安装', 55]] }),
    complications: [
      { id: 'nonunion', name: '骨不连', weight: 0.15, severity: 'severe', whenDays: 60, bodyFields: ['surgeryHistory'], note: '延长段迟迟不愈合' },
      { id: 'nerve_injury', name: '神经损伤', weight: 0.15, severity: 'severe', whenDays: 7, bodyFields: ['surgeryHistory'], note: '牵拉致足下垂、感觉减退' },
      { id: 'joint_stiffness', name: '关节僵硬', weight: 0.30, severity: 'moderate', whenDays: 45, bodyFields: ['surgeryHistory'], note: '长期外固定致膝踝活动受限' },
      { id: 'malalignment', name: '力线偏移', weight: 0.12, severity: 'moderate', whenDays: 60, bodyFields: ['height'], note: '延长不均致下肢不等长' },
    ],
    bodyFields: ['surgeryHistory', 'height'],
    note: '意愿·改造型；档案落点 height 由报告 / 用户给值（库不固定加多少厘米）；分级为本仓自评',
  },
  {
    id: 'x-prosth',
    legacyId: 'X.prosth',   // 0.7.25 起扩展条目用 x-<slug>；旧 id（X.*）留着兼容已落盘的数据
    name: '赛博义体植入术',
    alias: ['义体植入', '机械假体植入'],
    catalog: 'ext',
    codeVerified: false,
    chapter: '第十六章 其他手术',
    category: '植入物手术',
    grade: 4,
    intents: ['elective'],
    anesthesia: 'general',
    recoveryDays: 60,
    stages: stageTable('lap', '赛博义体植入术', { drop: ['position', 'pneumo', 'explore', 'main', 'count', 'verify'], rename: { prep: '体位·消毒铺巾·定位', exposure: '显露植入部位', closure: '逐层关闭·包扎', wake: '麻醉恢复·出室' }, minutes: { induction: 12, prep: 8, exposure: 15, closure: 15, wake: 23 }, add: [['exposure', 'implant', '植入体置入·骨性 / 筋膜固定', 60], ['implant', 'interface', '接口连接·通电测试', 25]] }),
    complications: [
      { id: 'rejection', name: '植入物排异', weight: 0.20, severity: 'severe', whenDays: 14, bodyFields: ['temperature'], note: '持续发热、植入区渗出' },
      { id: 'ssi', name: '植入区感染', weight: 0.15, severity: 'moderate', whenDays: 5, bodyFields: ['temperature'], note: '红肿热痛、需取出风险' },
      { id: 'interface_failure', name: '接口失灵', weight: 0.15, severity: 'moderate', whenDays: 30, bodyFields: ['surgeryHistory'], note: '信号不稳、动作迟滞' },
      { id: 'chronic_pain', name: '慢性疼痛', weight: 0.35, severity: 'mild', whenDays: 60, bodyFields: ['surgeryHistory'], note: '接口处长期钝痛、天气变化加重' },
    ],
    bodyFields: ['surgeryHistory', 'height', 'weight'],
    note: '意愿·改造型；本仓口径：不新增引擎能力映射（只有 canGestate / canImpregnate 两类可写），义体效果只在报告与身体档案里写',
  },

  // ===== 0.7.25 批 1：普外 / 腔镜二期（高频补齐：腔镜阑尾、开放胆囊、左右半结肠、远端胰腺） =====
  {
    id: '47.01',
    name: '腹腔镜阑尾切除术',
    alias: ['腔镜阑尾切除', 'LA'],
    catalog: 'national',
    codeVerified: false,
    chapter: '第九章 消化系统手术',
    category: '阑尾手术',
    grade: 2,
    intents: ['therapeutic', 'emergency'],
    anesthesia: 'general',
    recoveryDays: 5,
    stages: stageTable('lap', '阑尾切除·荷包缝合', { drop: ['position', 'prep', 'exposure', 'verify'], rename: { explore: '镜下探查·寻找阑尾', count: '清点·止血', closure: '解除气腹·缝合戳孔' }, minutes: { induction: 8, pneumo: 6, explore: 8, main: 20, count: 4, closure: 6, wake: 6 } }),
    complications: [
      { id: 'ssi', name: '戳孔感染', weight: 0.18, severity: 'mild', whenDays: 3, bodyFields: ['temperature'], note: '戳孔红肿渗液、低热' },
      { id: 'intra_abscess', name: '腹腔残余脓肿', weight: 0.14, severity: 'moderate', whenDays: 5, bodyFields: ['temperature', 'heartRate'], note: '持续发热、下腹压痛' },
      { id: 'ileus', name: '术后肠麻痹', weight: 0.16, severity: 'mild', whenDays: 2, bodyFields: ['temperature'], note: '腹胀、迟迟不排气' },
    ],
    bodyFields: ['surgeryHistory', 'temperature'],
    note: '与开放阑尾切除同一手术目标，只是入路不同；不涉及生殖器官，不影响生育能力。',
  },
  {
    id: '51.22',
    name: '胆囊切除术（开放）',
    alias: ['开腹胆囊切除'],
    catalog: 'national',
    codeVerified: false,
    chapter: '第九章 消化系统手术',
    category: '胆道手术',
    grade: 3,
    intents: ['therapeutic', 'emergency'],
    anesthesia: 'general',
    recoveryDays: 10,
    stages: stageTable('open', '胆囊切除·胆囊床处理', { drop: ['anesthesia', 'prep', 'exposure', 'verify'], rename: { incision: '右肋缘下切口', explore: '探查·显露胆囊三角', closure: '关腹' }, minutes: { induction: 8, position: 4, incision: 5, explore: 12, main: 35, count: 5, closure: 10, wake: 8 } }),
    complications: [
      { id: 'bile_leak', name: '胆漏', weight: 0.1, severity: 'moderate', whenDays: 4, bodyFields: ['temperature', 'heartRate'], note: '引流液呈胆汁色、右上腹不适' },
      { id: 'bile_duct_injury', name: '胆管损伤', weight: 0.03, severity: 'severe', whenDays: 2, bodyFields: ['temperature', 'heartRate'], note: '术后黄疸、腹痛加重' },
      { id: 'ssi', name: '切口感染', weight: 0.2, severity: 'mild', whenDays: 3, bodyFields: ['temperature'], note: '切口红肿渗液' },
    ],
    bodyFields: ['surgeryHistory', 'temperature'],
    note: '胆囊不是生殖器官，不影响生育能力。',
  },
  {
    id: '45.73',
    name: '右半结肠切除术',
    alias: ['右半结肠根治切除'],
    catalog: 'national',
    codeVerified: false,
    chapter: '第九章 消化系统手术',
    category: '肠手术',
    grade: 4,
    intents: ['therapeutic'],
    anesthesia: 'general',
    recoveryDays: 14,
    stages: stageTable('open', '右半结肠切除·回结肠吻合', { drop: ['anesthesia', 'prep', 'exposure', 'verify'], rename: { incision: '右腹直肌切口', explore: '探查·游离右半结肠', closure: '关腹' }, minutes: { induction: 10, position: 6, incision: 6, explore: 25, main: 90, count: 6, closure: 14, wake: 12 } }),
    complications: [
      { id: 'anastomotic_leak', name: '吻合口漏', weight: 0.08, severity: 'severe', whenDays: 5, bodyFields: ['temperature', 'heartRate'], note: '发热、腹痛、引流液浑浊' },
      { id: 'ileus', name: '术后肠梗阻', weight: 0.15, severity: 'moderate', whenDays: 4, bodyFields: ['temperature'], note: '腹胀、停止排气排便' },
      { id: 'ssi', name: '切口感染', weight: 0.22, severity: 'mild', whenDays: 3, bodyFields: ['temperature'], note: '切口红肿渗液' },
    ],
    bodyFields: ['surgeryHistory', 'temperature'],
    note: '结肠紧邻生殖器官，但切除结肠本身不改变妊娠 / 使孕能力（不改卵巢、子宫、睾丸）。',
  },
  {
    id: '45.75',
    name: '左半结肠切除术',
    alias: ['左半结肠根治切除'],
    catalog: 'national',
    codeVerified: false,
    chapter: '第九章 消化系统手术',
    category: '肠手术',
    grade: 4,
    intents: ['therapeutic'],
    anesthesia: 'general',
    recoveryDays: 14,
    stages: stageTable('open', '左半结肠切除·结肠吻合', { drop: ['anesthesia', 'prep', 'exposure', 'verify'], rename: { incision: '左腹直肌切口', explore: '探查·游离左半结肠', closure: '关腹' }, minutes: { induction: 10, position: 6, incision: 6, explore: 22, main: 85, count: 6, closure: 14, wake: 12 } }),
    complications: [
      { id: 'anastomotic_leak', name: '吻合口漏', weight: 0.09, severity: 'severe', whenDays: 5, bodyFields: ['temperature', 'heartRate'], note: '发热、腹痛、引流液浑浊' },
      { id: 'ileus', name: '术后肠梗阻', weight: 0.14, severity: 'moderate', whenDays: 4, bodyFields: ['temperature'], note: '腹胀、停止排气排便' },
      { id: 'ssi', name: '切口感染', weight: 0.2, severity: 'mild', whenDays: 3, bodyFields: ['temperature'], note: '切口红肿渗液' },
    ],
    bodyFields: ['surgeryHistory', 'temperature'],
    note: '同右半结肠切除：不改变妊娠 / 使孕能力（不动生殖器官本体）。',
  },
  {
    id: '52.51',
    // 0.7.26 抽查：**编码存疑** —— 52.51 疑为"近端胰切除"、远端疑为 52.52；本仓联网只核到
    // 两个编码都存在（未核到名称确证）→ 不擅自改 id，把候选登记在 codeCandidates，待人工核。
    name: '远端胰腺切除术',
    alias: ['胰体尾切除'],
    codeCandidates: ['52.52'],
    catalog: 'national',
    codeVerified: false,
    chapter: '第九章 消化系统手术',
    category: '胰腺手术',
    grade: 4,
    intents: ['therapeutic'],
    anesthesia: 'general',
    recoveryDays: 18,
    stages: stageTable('open', '胰体尾切除·胰肠吻合', { drop: ['anesthesia', 'prep', 'exposure', 'verify'], rename: { incision: '上腹横切口', explore: '探查·游离胰体尾', closure: '关腹·置引流' }, minutes: { induction: 10, position: 6, incision: 6, explore: 30, main: 110, count: 6, closure: 16, wake: 14 } }),
    complications: [
      { id: 'pancreatic_fistula', name: '胰瘘', weight: 0.2, severity: 'severe', whenDays: 6, bodyFields: ['temperature', 'heartRate'], note: '引流液淀粉酶升高、腹痛' },
      { id: 'bleeding', name: '术后出血', weight: 0.08, severity: 'severe', whenDays: 1, bodyFields: ['heartRate', 'bloodPressure'], note: '心率增快、血压下降' },
      { id: 'ssi', name: '切口感染', weight: 0.18, severity: 'mild', whenDays: 3, bodyFields: ['temperature'], note: '切口红肿渗液' },
    ],
    bodyFields: ['surgeryHistory', 'temperature'],
    note: '胰腺不是生殖器官；不影响生育能力。',
  },

  // ===== 0.7.25 批 2：骨科与泌尿（四肢骨折内固定、膝关节镜、部分肾切除、体外碎石） =====
  {
    id: '79.35',
    name: '股骨骨折切开复位内固定术',
    alias: ['股骨内固定', 'ORIF 股骨'],
    catalog: 'national',
    codeVerified: false,
    chapter: '第十四章 肌肉骨骼系统手术',
    category: '骨折内固定',
    grade: 3,
    intents: ['emergency', 'therapeutic'],
    anesthesia: 'regional',
    recoveryDays: 90,
    stages: stageTable('open', '骨折复位·钢板/髓内钉固定', { drop: ['anesthesia', 'prep', 'verify'], rename: { incision: '骨折端切口', explore: '显露骨折端·清理', exposure: '复位·临时固定', closure: '逐层缝合·包扎' }, minutes: { induction: 10, position: 8, incision: 8, explore: 15, exposure: 12, main: 60, count: 5, closure: 12, wake: 10 } }),
    complications: [
      { id: 'infection', name: '深部感染', weight: 0.06, severity: 'severe', whenDays: 7, bodyFields: ['temperature', 'heartRate'], note: '局部红肿热痛、发热' },
      { id: 'dvt', name: '下肢深静脉血栓', weight: 0.1, severity: 'moderate', whenDays: 5, bodyFields: ['heartRate'], note: '小腿肿胀疼痛' },
      { id: 'fixation_failure', name: '内固定失效', weight: 0.07, severity: 'moderate', whenDays: 30, bodyFields: ['surgeryHistory'], note: '复查见内固定松动 / 移位' },
    ],
    bodyFields: ['surgeryHistory', 'temperature'],
    note: '四肢骨折内固定不涉及生殖器官；术后活动受限是暂时的。',
  },
  {
    id: '79.36',
    name: '胫骨骨折切开复位内固定术',
    alias: ['胫骨内固定'],
    catalog: 'national',
    codeVerified: false,
    chapter: '第十四章 肌肉骨骼系统手术',
    category: '骨折内固定',
    grade: 3,
    intents: ['emergency', 'therapeutic'],
    anesthesia: 'regional',
    recoveryDays: 90,
    stages: stageTable('open', '骨折复位·钢板固定', { drop: ['anesthesia', 'prep', 'verify'], rename: { incision: '胫骨前内侧切口', explore: '显露骨折端', exposure: '复位·钢板固定', closure: '逐层缝合·包扎' }, minutes: { induction: 10, position: 6, incision: 6, explore: 12, exposure: 10, main: 55, count: 5, closure: 10, wake: 10 } }),
    complications: [
      { id: 'infection', name: '深部感染', weight: 0.07, severity: 'severe', whenDays: 7, bodyFields: ['temperature', 'heartRate'], note: '局部红肿热痛、发热' },
      { id: 'delayed_union', name: '骨不连 / 延迟愈合', weight: 0.08, severity: 'moderate', whenDays: 60, bodyFields: ['surgeryHistory'], note: '复查见骨痂少、局部压痛' },
      { id: 'compartment', name: '骨筋膜室综合征', weight: 0.03, severity: 'critical', whenDays: 1, bodyFields: ['heartRate', 'bloodPressure'], note: '小腿剧痛、被动牵拉痛' },
    ],
    bodyFields: ['surgeryHistory', 'temperature'],
    note: '不涉及生殖器官，不影响生育能力。',
  },
  {
    id: '80.6',
    name: '半月板切除术（关节镜）',
    alias: ['关节镜半月板切除'],
    catalog: 'national',
    codeVerified: false,
    chapter: '第十四章 肌肉骨骼系统手术',
    category: '膝关节镜',
    grade: 3,
    intents: ['therapeutic'],
    anesthesia: 'regional',
    recoveryDays: 45,
    stages: stageTable('endo', '镜下探查·半月板切除', { drop: ['induction', 'verify', 'closure'], rename: { anesthesia: '椎管内麻醉', position: '仰卧位·患肢固定', prep: '关节镜器械准备', scope: '关节镜入路', inspect: '镜下探查关节腔', hemostasis: '冲洗·止血' }, minutes: { anesthesia: 12, position: 5, prep: 5, scope: 6, inspect: 8, main: 35, hemostasis: 5, withdraw: 3, wake: 8 } }),
    complications: [
      { id: 'effusion', name: '关节积液', weight: 0.22, severity: 'mild', whenDays: 5, bodyFields: ['temperature'], note: '膝关节肿胀、活动受限' },
      { id: 'infection', name: '关节内感染', weight: 0.02, severity: 'severe', whenDays: 4, bodyFields: ['temperature', 'heartRate'], note: '关节红肿热痛、发热' },
      { id: 'stiffness', name: '关节僵硬', weight: 0.12, severity: 'moderate', whenDays: 30, bodyFields: ['surgeryHistory'], note: '屈伸范围受限' },
    ],
    bodyFields: ['surgeryHistory', 'temperature'],
    note: '膝关节镜远离生殖器官，不影响生育能力。',
  },
  {
    id: '55.4',
    name: '部分肾切除术',
    alias: ['肾部分切除', '保肾手术'],
    catalog: 'national',
    codeVerified: false,
    chapter: '第十章 泌尿系统手术',
    category: '肾脏手术',
    grade: 4,
    intents: ['therapeutic'],
    anesthesia: 'general',
    recoveryDays: 14,
    stages: stageTable('open', '肾部分切除·创面止血', { drop: ['anesthesia', 'prep', 'exposure', 'verify'], rename: { incision: '腰部切口', explore: '探查·游离肾脏', closure: '关腹·置引流' }, minutes: { induction: 10, position: 8, incision: 8, explore: 20, main: 70, count: 5, closure: 14, wake: 12 } }),
    complications: [
      { id: 'bleeding', name: '术后出血', weight: 0.1, severity: 'severe', whenDays: 1, bodyFields: ['heartRate', 'bloodPressure'], note: '引流血性液多、心率增快' },
      { id: 'urine_leak', name: '尿漏', weight: 0.08, severity: 'moderate', whenDays: 4, bodyFields: ['temperature'], note: '引流液清亮量多' },
      { id: 'infection', name: '切口 / 深部感染', weight: 0.12, severity: 'mild', whenDays: 4, bodyFields: ['temperature'], note: '切口红肿、发热' },
    ],
    bodyFields: ['surgeryHistory', 'temperature'],
    note: '肾脏紧邻生殖器官，但部分肾切除不动卵巢 / 睾丸 / 子宫 → 不改变妊娠 / 使孕能力。',
  },
  {
    id: '98.51',
    name: '体外冲击波碎石术',
    alias: ['ESWL', '体外碎石'],
    catalog: 'national',
    codeVerified: false,
    chapter: '第十六章 其他手术',
    category: '泌尿系结石',
    grade: 1,
    intents: ['therapeutic'],
    anesthesia: 'none',
    recoveryDays: 3,
    stages: stageTable('endo', '定位·冲击波碎石', { drop: ['induction', 'prep', 'verify', 'closure'], rename: { anesthesia: '镇痛（必要时）', position: '俯卧 / 仰卧位·定位', scope: '定位结石', inspect: 'X 线 / 超声监视', hemostasis: '观察排石' }, minutes: { anesthesia: 3, position: 5, scope: 8, inspect: 6, main: 30, hemostasis: 4, withdraw: 2, wake: 4 } }),
    complications: [
      { id: 'hematuria', name: '血尿', weight: 0.3, severity: 'mild', whenDays: 1, bodyFields: ['temperature'], note: '尿色发红，多为一过性' },
      { id: 'renal_colic', name: '肾绞痛', weight: 0.18, severity: 'moderate', whenDays: 2, bodyFields: ['heartRate'], note: '腰腹绞痛、恶心' },
      { id: 'stone_street', name: '石街（排石不畅）', weight: 0.1, severity: 'moderate', whenDays: 3, bodyFields: ['temperature'], note: '输尿管走行区疼痛、少尿' },
    ],
    bodyFields: ['surgeryHistory', 'temperature'],
    note: '无切口的非侵入操作；不涉及生殖器官，不影响生育能力。',
  },

  // ===== 0.7.25 批 3：妇产与乳腺（腔镜全子宫、单侧输卵管、宫颈锥切、乳腺两术式） =====
  {
    id: '68.51',
    // 0.7.26 抽查：编码 68.51 经两处独立来源核到 = **LAVH**（腹腔镜辅助阴式全子宫切除术），
    // 不是笼统的"腔镜全子宫切除" → 按文件头第 2 条只改 id / name（id 保留 68.51，把名字改准）。
    name: '腹腔镜辅助阴式全子宫切除术（LAVH）',
    alias: ['腔镜子宫全切', 'LAVH', 'TLH'],
    catalog: 'national',
    codeVerified: false,
    chapter: '第十二章 女性生殖器官手术',
    category: '子宫手术',
    grade: 4,
    intents: ['therapeutic'],
    anesthesia: 'general',
    recoveryDays: 21,
    stages: stageTable('lap', '子宫全切·阴道残端缝合', { drop: ['prep', 'exposure', 'verify'], rename: { position: '截石位·消毒铺巾', pneumo: '建立气腹·穿刺器置入', explore: '镜下探查盆腔', count: '清点·止血', closure: '解除气腹·缝合戳孔' }, minutes: { induction: 10, position: 8, pneumo: 8, explore: 15, main: 70, count: 6, closure: 8, wake: 10 } }),
    complications: [
      { id: 'bleeding', name: '术后出血', weight: 0.1, severity: 'severe', whenDays: 1, bodyFields: ['heartRate', 'bloodPressure'], note: '引流血性液多、心率增快' },
      { id: 'infection', name: '盆腔感染', weight: 0.12, severity: 'moderate', whenDays: 5, bodyFields: ['temperature', 'heartRate'], note: '发热、下腹压痛' },
      { id: 'urinary_injury', name: '泌尿系损伤', weight: 0.04, severity: 'severe', whenDays: 3, bodyFields: ['temperature'], note: '尿量异常 / 漏尿' },
    ],
    bodyFields: ['surgeryHistory', 'temperature'],
    // 0.7.27（用户裁示"可以放宽"）：凡把生殖器官**整体拿掉**的术式都写能力位 —— 本条是子宫全切，
    // 与 68.4 同口径，补 canGestate:false（原写法只给 62.4 / 68.4 / 65.6 三条）。
    capabilities: { canGestate: false },
    note: '切除子宫 = 永久失去妊娠能力（解剖上必然影响生育）。0.7.27 起口径放宽：本条与 68.4 一样写 canGestate:false（引擎侧关掉可妊娠），不再只靠 note 说明。',
  },
  {
    id: '66.4',
    name: '单侧输卵管切除术',
    alias: ['输卵管切除（单侧）'],
    catalog: 'national',
    codeVerified: false,
    chapter: '第十二章 女性生殖器官手术',
    category: '输卵管手术',
    grade: 3,
    intents: ['therapeutic', 'emergency'],
    anesthesia: 'general',
    recoveryDays: 10,
    stages: stageTable('open', '输卵管切除·残端处理', { drop: ['anesthesia', 'prep', 'exposure', 'verify'], rename: { incision: '下腹横切口', explore: '探查·游离输卵管', closure: '关腹' }, minutes: { induction: 8, position: 5, incision: 5, explore: 12, main: 30, count: 4, closure: 8, wake: 8 } }),
    complications: [
      { id: 'bleeding', name: '残端出血', weight: 0.06, severity: 'moderate', whenDays: 1, bodyFields: ['heartRate'], note: '下腹坠痛、引流血性液' },
      { id: 'infection', name: '盆腔感染', weight: 0.12, severity: 'moderate', whenDays: 4, bodyFields: ['temperature'], note: '发热、下腹压痛' },
      { id: 'adhesion', name: '盆腔粘连', weight: 0.18, severity: 'mild', whenDays: 30, bodyFields: ['surgeryHistory'], note: '慢性下腹隐痛' },
    ],
    bodyFields: ['surgeryHistory', 'temperature'],
    note: '只切一侧：对侧输卵管与双侧卵巢保留 → 妊娠能力通常不受影响，但若对侧已有病变 / 阻塞，风险上升。这里不改引擎能力位（不是"整体拿掉"）。',
  },
  {
    id: '67.2',
    name: '宫颈锥形切除术',
    alias: ['宫颈锥切', 'CKC'],
    catalog: 'national',
    codeVerified: false,
    chapter: '第十二章 女性生殖器官手术',
    category: '宫颈手术',
    grade: 2,
    intents: ['therapeutic'],
    anesthesia: 'regional',
    recoveryDays: 14,
    stages: stageTable('open', '锥形切除宫颈组织·止血', { drop: ['anesthesia', 'prep', 'explore', 'exposure', 'count', 'verify'], rename: { position: '截石位·消毒铺巾', incision: '暴露宫颈', main: '锥形切除宫颈组织·止血', closure: '创面止血·填纱' }, minutes: { induction: 6, position: 5, incision: 3, main: 20, closure: 8, wake: 6 } }),
    complications: [
      { id: 'bleeding', name: '创面出血', weight: 0.1, severity: 'moderate', whenDays: 1, bodyFields: ['heartRate'], note: '阴道流血量多' },
      { id: 'stenosis', name: '宫颈管狭窄', weight: 0.06, severity: 'moderate', whenDays: 60, bodyFields: ['surgeryHistory'], note: '经血排出不畅、痛经' },
      { id: 'infection', name: '术后感染', weight: 0.1, severity: 'mild', whenDays: 5, bodyFields: ['temperature'], note: '分泌物异味、低热' },
    ],
    bodyFields: ['surgeryHistory', 'temperature'],
    note: '子宫 / 卵巢仍在 → 不改引擎能力位；但锥切可能影响宫颈机能（与早产风险相关），写在这里供术前谈话与孕产判定参考。',
  },
  {
    id: '85.23',
    name: '乳房象限切除术',
    alias: ['乳腺区段切除', '保乳手术'],
    catalog: 'national',
    codeVerified: false,
    chapter: '第十五章 体被系统手术',
    category: '乳房手术',
    grade: 3,
    intents: ['therapeutic'],
    anesthesia: 'general',
    recoveryDays: 10,
    stages: stageTable('surface', '肿物象限切除·缝合', { drop: ['marking', 'exposure', 'verify'], rename: { anesthesia: '全身麻醉', prep: '体位·消毒铺巾', incision: '弧形切口·显露肿物', closure: '止血·分层缝合', bandage: '加压包扎' }, minutes: { anesthesia: 8, prep: 5, incision: 6, main: 40, closure: 12, bandage: 5, wake: 8 } }),
    complications: [
      { id: 'ssi', name: '切口感染', weight: 0.15, severity: 'mild', whenDays: 3, bodyFields: ['temperature'], note: '切口红肿渗液' },
      { id: 'seroma', name: '皮下积液', weight: 0.2, severity: 'mild', whenDays: 5, bodyFields: ['surgeryHistory'], note: '术区波动感、穿刺抽出淡血性液' },
      { id: 'recurrence', name: '局部复发', weight: 0.1, severity: 'moderate', whenDays: 60, bodyFields: ['surgeryHistory'], note: '复查见术区新病灶' },
    ],
    bodyFields: ['surgeryHistory', 'temperature'],
    note: '乳房不是生殖器官，不影响妊娠 / 使孕能力（读者容易以为"胸部手术会影响哺乳以外的生育"，故写明）。',
  },
  {
    id: '85.45',
    name: '乳腺癌根治术',
    alias: ['乳癌根治', '改良根治'],
    catalog: 'national',
    codeVerified: false,
    chapter: '第十五章 体被系统手术',
    category: '乳房手术',
    grade: 4,
    intents: ['therapeutic'],
    anesthesia: 'general',
    recoveryDays: 21,
    stages: stageTable('open', '乳房切除·腋窝淋巴结清扫', { drop: ['anesthesia', 'prep', 'exposure', 'count', 'verify'], rename: { incision: '梭形切口·游离皮瓣', explore: '探查·确定切除范围', main: '乳房切除·腋窝淋巴结清扫', closure: '皮瓣对合·置引流' }, minutes: { induction: 10, position: 6, incision: 20, explore: 15, main: 100, closure: 25, wake: 12 } }),
    complications: [
      { id: 'ssi', name: '皮瓣坏死 / 感染', weight: 0.18, severity: 'moderate', whenDays: 5, bodyFields: ['temperature'], note: '皮瓣发黑、切口渗液' },
      { id: 'lymphedema', name: '上肢淋巴水肿', weight: 0.2, severity: 'moderate', whenDays: 60, bodyFields: ['surgeryHistory'], note: '患侧上肢肿胀' },
      { id: 'bleeding', name: '术后出血', weight: 0.06, severity: 'severe', whenDays: 1, bodyFields: ['heartRate', 'bloodPressure'], note: '引流量骤增、心率增快' },
    ],
    bodyFields: ['surgeryHistory', 'temperature'],
    note: '不改变妊娠 / 使孕能力（不动卵巢 / 子宫）；术后辅助治疗对生育的影响属医疗侧，不在本库。',
  },

  // ===== 0.7.25 批 4：体表 / 内镜 / 意愿改造（结肠镜、毛发移植、种植牙、屈光矫正、纹身祛除） =====
  {
    id: '45.23',
    name: '结肠镜检查',
    alias: ['肠镜', '全结肠镜'],
    catalog: 'national',
    codeVerified: false,
    chapter: '第九章 消化系统手术',
    category: '内镜检查',
    grade: 1,
    intents: ['therapeutic'],
    anesthesia: 'none',
    recoveryDays: 1,
    stages: stageTable('endo', '进镜观察·必要时活检', { drop: ['induction', 'verify', 'closure'], rename: { anesthesia: '镇静（必要时）', position: '左侧卧位', prep: '肠道准备确认·器械准备', scope: '经肛进镜', inspect: '逐段观察黏膜', hemostasis: '活检 / 止血处理' }, minutes: { anesthesia: 3, position: 3, prep: 5, scope: 5, inspect: 15, main: 20, hemostasis: 5, withdraw: 3, wake: 5 } }),
    complications: [
      { id: 'bleeding', name: '活检后出血', weight: 0.06, severity: 'mild', whenDays: 1, bodyFields: ['temperature'], note: '少量便血' },
      { id: 'perforation', name: '肠穿孔', weight: 0.01, severity: 'critical', whenDays: 1, bodyFields: ['heartRate', 'bloodPressure', 'temperature'], note: '剧烈腹痛、腹膜炎体征' },
    ],
    bodyFields: ['surgeryHistory', 'temperature'],
    note: '检查性操作（无切口）；不涉及生殖器官。',
  },
  {
    id: 'x-hair-transplant',
    name: '毛发移植术',
    alias: ['植发', '毛囊单位移植'],
    catalog: 'ext',
    codeVerified: false,
    chapter: '第十五章 体被系统手术',
    category: '毛发移植',
    grade: 1,
    intents: ['elective'],
    anesthesia: 'local',
    recoveryDays: 14,
    stages: stageTable('surface', '毛囊单位提取·种植', { drop: ['marking', 'exposure', 'verify'], rename: { anesthesia: '局部麻醉（含肿胀液）', prep: '供区 / 受区消毒铺巾', incision: '供区钻取毛囊单位', main: '毛囊单位提取·种植', closure: '受区清点·包扎', bandage: '供区加压包扎' }, minutes: { anesthesia: 10, prep: 8, incision: 20, main: 180, closure: 10, bandage: 5, wake: 5 } }),
    complications: [
      { id: 'ssi', name: '供 / 受区感染', weight: 0.06, severity: 'mild', whenDays: 4, bodyFields: ['temperature'], note: '局部红肿渗液' },
      { id: 'effluvium', name: '暂时性脱发', weight: 0.25, severity: 'mild', whenDays: 30, bodyFields: ['surgeryHistory'], note: '术后 1~3 个月移植区毛发脱落（多为暂时）' },
    ],
    bodyFields: ['surgeryHistory'],
    note: '意愿 · 改造型：不治任何病症，只写身体档案；不影响生育能力。',
  },
  {
    id: 'x-dental-implant',
    name: '种植牙植入术',
    alias: ['牙种植', '种植体植入'],
    catalog: 'ext',
    codeVerified: false,
    chapter: '第五章 鼻、口、咽部手术',
    category: '口腔种植',
    grade: 1,
    intents: ['elective'],
    anesthesia: 'local',
    recoveryDays: 60,
    stages: stageTable('surface', '备洞·植入种植体', { drop: ['marking', 'exposure', 'verify'], rename: { anesthesia: '局部浸润麻醉', prep: '口腔消毒铺巾', incision: '牙槽嵴切口·翻瓣', main: '备洞·植入种植体', closure: '缝合·压迫止血', bandage: '术后咬纱止血' }, minutes: { anesthesia: 5, prep: 5, incision: 8, main: 40, closure: 8, bandage: 3, wake: 3 } }),
    complications: [
      { id: 'ssi', name: '种植体周围感染', weight: 0.1, severity: 'mild', whenDays: 7, bodyFields: ['temperature'], note: '局部红肿、疼痛' },
      { id: 'failure', name: '种植体失败（松动）', weight: 0.05, severity: 'moderate', whenDays: 60, bodyFields: ['surgeryHistory'], note: '复查见种植体松动 / 脱落' },
    ],
    bodyFields: ['surgeryHistory'],
    note: '意愿 · 改造型：不治病症、不影响生育能力。',
  },
  {
    id: 'x-lasik',
    name: '屈光矫正术',
    alias: ['LASIK', '近视激光手术'],
    catalog: 'ext',
    codeVerified: false,
    chapter: '第三章 眼部手术',
    category: '屈光手术',
    grade: 1,
    intents: ['elective'],
    anesthesia: 'local',
    recoveryDays: 7,
    stages: stageTable('surface', '制作角膜瓣·激光切削', { drop: ['marking', 'exposure', 'verify'], rename: { anesthesia: '表面麻醉滴眼', prep: '眼部消毒铺巾·开睑', incision: '制作角膜瓣', main: '激光切削·复位角膜瓣', closure: '冲洗·戴保护镜', bandage: '术后滴眼药' }, minutes: { anesthesia: 3, prep: 5, incision: 4, main: 12, closure: 5, bandage: 3, wake: 3 } }),
    complications: [
      { id: 'dry_eye', name: '干眼', weight: 0.3, severity: 'mild', whenDays: 30, bodyFields: ['surgeryHistory'], note: '眼干、异物感' },
      { id: 'undercorrection', name: '欠矫 / 回退', weight: 0.1, severity: 'mild', whenDays: 60, bodyFields: ['surgeryHistory'], note: '视力回退' },
      { id: 'infection', name: '角膜感染', weight: 0.01, severity: 'severe', whenDays: 3, bodyFields: ['temperature'], note: '眼痛、畏光、视力下降' },
    ],
    bodyFields: ['surgeryHistory'],
    note: '意愿 · 改造型：不治病症、不影响生育能力。',
  },
  {
    id: 'x-tattoo-removal',
    name: '纹身祛除术',
    alias: ['洗纹身', '激光祛纹身'],
    catalog: 'ext',
    codeVerified: false,
    chapter: '第十五章 体被系统手术',
    category: '体表祛除',
    grade: 1,
    intents: ['elective'],
    anesthesia: 'local',
    recoveryDays: 10,
    stages: stageTable('surface', '激光 / 手术祛除色素', { drop: ['marking', 'exposure', 'verify'], rename: { anesthesia: '局部麻醉 / 表面麻醉', prep: '术区消毒铺巾', incision: '术区准备', main: '激光 / 手术祛除色素', closure: '创面处理·敷料', bandage: '覆盖敷料' }, minutes: { anesthesia: 5, prep: 4, incision: 3, main: 25, closure: 8, bandage: 3, wake: 3 } }),
    complications: [
      { id: 'scar', name: '瘢痕 / 色素改变', weight: 0.25, severity: 'mild', whenDays: 60, bodyFields: ['surgeryHistory'], note: '术区留疤或色沉' },
      { id: 'ssi', name: '创面感染', weight: 0.08, severity: 'mild', whenDays: 4, bodyFields: ['temperature'], note: '创面红肿渗液' },
    ],
    bodyFields: ['surgeryHistory'],
    note: '意愿 · 改造型：不治病症、不影响生育能力。',
  },
];
