import * as D from '/home/user/ruby-phone/apps/pixiv/pixiv-data.js';
console.log('normalizeChapter nope num =', JSON.stringify(D.normalizeChapter({ num: 'nope', content: 'x' }, 4).num));
console.log('normalizeChapter 0 num =', JSON.stringify(D.normalizeChapter({ num: 0, content: 'x' }, 0).num));
const nov = D.normalizeNovel({ id: 'n1', hearts: 999999, chapters: [{ num: 1, hearts: 10 }, { num: 2, hearts: 20 }] });
console.log('normalizeNovel hearts(存量比逐章大) =', nov.hearts, '（应 20）');
const hb = D.deriveHeatBase(5000, 98 * 1 + 3);
console.log('deriveHeatBase 样例 =', hb);
console.log('上界 =', D.deriveHeatBase(999999999, 98));
const h1 = D.deriveChapterHearts(1000, 1), h2 = D.deriveChapterHearts(1000, 2), h3 = D.deriveChapterHearts(1000, 3);
console.log('逐章 =', h1, h2, h3, '首章最大?', h1 >= Math.max(h2, h3));
const st = D.resolveWritingStyle({ writingStyles: D.PIXIV_WRITING_STYLES }, 'pixiv_style_knife');
console.log('style explicit =', JSON.stringify(st));
console.log('style missing =', JSON.stringify(D.resolveWritingStyle({ writingStyles: D.PIXIV_WRITING_STYLES }, 'nope')));
console.log('style none_enabled =', JSON.stringify(D.resolveWritingStyle({ writingStyles: D.PIXIV_WRITING_STYLES.map(s => ({ ...s, enabled: false })) }, '')));
const off = D.PIXIV_WRITING_STYLES.map(s => ({ ...s, enabled: false }));
off[0].enabled = true;
console.log('style random(唯一开) =', JSON.stringify(D.resolveWritingStyle({ writingStyles: off }, '')));
const pd = D.pickDiverseAuthors(D.PIXIV_BUILT_IN_AUTHORS.filter(a => D.isActivePixivType(a.type)), 3, '', 7);
console.log('pickDiverseAuthors keys =', Object.keys(pd).join(','), 'picked=', pd.picked.length, 'considered=', pd.considered, 'matched=', pd.matched);
console.log('isActivePixivType official =', D.isActivePixivType('official'), ' doujin_writer =', D.isActivePixivType('doujin_writer'));
console.log('coldOfNovelId n1 =', D.coldOfNovelId('n1'), '范围检查 2000..20000');
console.log('parseCommentsBlock 空 =', JSON.stringify(D.parseCommentsBlock('')));
console.log('toDisplayParagraphs =', JSON.stringify(D.toDisplayParagraphs('一\n\n二\n<script>x</script>')));
console.log('PIXIV_COMMENT_DELIM =', D.PIXIV_COMMENT_DELIM);
